### PR TITLE
fix for Rayleigh sponge

### LINKED ISSUE #2158: GPU compilation error in `rayleigh_sponge_cache`
GPU compilation for the `moist Held-Suarez` simulation generates a compilation error in `rayleigh_sponge_cache`. The full error message can be found here: https://buildkite.com/clima/climaatmos-target-gpu-simulations/builds/71#018acda7-0c93-48d9-881e-90c321d2b525
cc: @simonbyrne

### PR DESCRIPTION
**Pull request by simonbyrne**
## Purpose 
Fixes #2158

## Content

----
- [x] I have read and checked the items on the review checklist.

### CODE REVIEW

**Comment by simonbyrne** [comment]
https://buildkite.com/clima/climaatmos-target-gpu-simulations/builds/87

**Comment by charleskawczynski** [comment]
@simonbyrne, I rebased to see how the moist gpu simulation runs, now that it's merged.

**Comment by charleskawczynski** [comment]
Looks like it broke a line down on the same thing, so let's merge this and see what happens next.

**Pull request merged**
