### PR TITLE
Update dependencies

### PR DESCRIPTION
**Pull request by charleskawczynski**
This PR upgrades the dependencies, including ClimaTimeSteppers. The new version fuses some operations, resulting in precision error differences.

### CODE REVIEW

**Comment by szy21** [comment]
Ah, I just did #2140, but I didn't update ClimaTimesteppers I think.

**Comment by charleskawczynski** [comment]
> Ah, I just did https://github.com/CliMA/ClimaAtmos.jl/pull/2140, but I didn't update ClimaTimesteppers I think.

No problem, we need to bump the ref counter for this one anyway

**Pull request merged**
