### PR TITLE
use implicit solver in the gpu prognostic edmf job

### PR DESCRIPTION
**Pull request by szy21**
## Content

----
- [ ] I have read and checked the items on the review checklist.

### CODE REVIEW

**Comment by charleskawczynski** [comment]
Going to rebase to see the current state of things

**Comment by charleskawczynski** [comment]
Looks like this is working now 🙂

**Comment by charleskawczynski** [comment]
@szy21, should we merge this?

**Comment by szy21** [comment]
I updated this PR. Here is the error: https://buildkite.com/clima/climaatmos-ci/builds/18074#018eaa40-5e56-40d3-8d5b-a796cf4d4043/200-289

**Pull request merged**
