### PR TITLE
configure CUDA in longrun pipeline

### PR DESCRIPTION
**Pull request by szy21**
## Purpose 

The longrun buildkite is failing: https://buildkite.com/clima/climaatmos-longruns/builds/1237#018bbcf8-52bf-4a31-b208-3edb0324d0e9/172-864. This PR tries to fix it.

## Content

----
- [ ] I have read and checked the items on the review checklist.

### CODE REVIEW

**Comment by szy21** [comment]
This doesn't work: https://buildkite.com/clima/climaatmos-longruns/builds/1238#018bc026-3f80-4c34-8aba-4742da4b893c. @charleskawczynski Any idea what we should do? We also don't run anything on GPU in the longrun now.

**Comment by charleskawczynski** [comment]
I think we can/need to remove `julia --project=examples -e 'using CUDA; CUDA.precompile_runtime()'` below (`CUDA` is no longer in the `examples` environment)

**Comment by szy21** [comment]
Yeah, but it seems the error is from this line `- "julia --project=cuda_env -e 'using Pkg; Pkg.resolve(); Pkg.instantiate(;verbose=true);using CUDA; CUDA.precompile_runtime()'"`:

> ERROR: expected package `CUDA [052768ef]` to be registered

**Comment by szy21** [comment]
I got the same error after removing `using CUDA` in the `examples` environment: https://buildkite.com/clima/climaatmos-longruns/builds/1239#018bc051-3dad-4640-acf1-2d03cfe84ce5

**Comment by charleskawczynski** [comment]
it looks like it's fixed now? buildkite ran most of the jobs-- it's at least passed the init stage

**Comment by szy21** [comment]
> it looks like it's fixed now? buildkite ran most of the jobs-- it's at least passed the init stage

Oh, no, I meant the longrun buildkite: https://buildkite.com/clima/climaatmos-longruns/builds/1239#018bc051-3dad-4640-acf1-2d03cfe84ce5 (build 1239)

**Comment by charleskawczynski** [comment]
Ah, right

**Comment by charleskawczynski** [comment]
I think we maybe need to instantiate the project first?

**Comment by szy21** [comment]
> I think we maybe need to instantiate the project first?

Thanks! It passes the init stage now: https://buildkite.com/clima/climaatmos-longruns/builds/1240 Most experiments are failing...but that's a different problem:)

**Comment by szy21** [comment]
Should we merge this in? There are still some longrun failures but for different reasons I think.

**Comment by szy21** [comment]
I'll make this ready for merge queue first as right now it takes forever :)

**Review by charleskawczynski — APPROVED** [review]

**Pull request merged**
