### PR TITLE
Remove unused fieldvector

### PR DESCRIPTION
**Pull request by charleskawczynski**
Followup to #2130

### CODE REVIEW

**Comment by charleskawczynski** [comment]
Why is
```julia
        Fields.bycolumn(axes(Y.c)) do colidx
            precipitation_tendency!(p.Yₜ, Y, p, t, colidx, p.precip_model)
        end # TODO: Set the diagnostics without computing the tendency.
```
used in the diagnostics? cc @trontrytel . Can we split this into precompute and add a function that adds fluxes so that we can remove `p.Yₜ`?

**Comment by trontrytel** [comment]
Not sure why? Not wanting to cache more things and or duplicate the code?

I don't have the bandwidth to fix this this week. Feel free to open an issue and tag me on it. I can try getting it done before the next sprint

> used in the diagnostics? cc @trontrytel . Can we split this into precompute and add a function that adds fluxes so that we can remove `p.Yₜ`?

**Comment by szy21** [comment]
I think we might use it to make sure the precipitation tendency is consistent with the state, as we call `set_precomputed_quantities!` in the diagnostics which updates the thermo state. It might be ok to remove it (i.e. I think it's ok if the diagnostics we save are slightly inconsistent, but maybe other people have different opinions.)

**Comment by charleskawczynski** [comment]
> I think we might use it to make sure the precipitation tendency is consistent with the state, as we call `set_precomputed_quantities!` in the diagnostics which updates the thermo state. It might be ok to remove it (i.e. I think it's ok if the diagnostics we save are slightly inconsistent, but maybe other people have different opinions.)

I think it's fine to precompute things needed for precipitation tendencies, but the precip tendendencies themselves don't seem to be used in the diagnostics-- Also if they are, then I think we can get them from the integrator?

**Comment by charleskawczynski** [comment]
@trontrytel, for now, I've just wrapped the tendency updates in `if`-blocks (`if !isnothing(Yₜ); Yₜ.var += ...; end`), so that we can pass in `nothing` from diagnostics-- all other quantities are computed (so `p` should be appropriately updated). Is this okay for now?

**Comment by szy21** [comment]
> > I think we might use it to make sure the precipitation tendency is consistent with the state, as we call `set_precomputed_quantities!` in the diagnostics which updates the thermo state. It might be ok to remove it (i.e. I think it's ok if the diagnostics we save are slightly inconsistent, but maybe other people have different opinions.)
> 
> I think it's fine to precompute things needed for precipitation tendencies, but the precip tendendencies themselves don't seem to be used in the diagnostics-- Also if they are, then I think we can get them from the integrator?

We calculate col_integrated_rain and col_integrated_snow in `precipitation_tendency!`, that's probably why we call it here. We can move them somewhere else though - we don't need them in the tendency.

**Comment by trontrytel** [comment]
> @trontrytel, for now, I've just wrapped the tendency updates in `if`-blocks (`if !isnothing(Yₜ); Yₜ.var += ...; end`), so that we can pass in `nothing` from diagnostics-- all other quantities are computed (so `p` should be appropriately updated). Is this okay for now?

Sounds good. Apologies it's such a mess over there. It would be great to allocate some time and straighten things up (looking at myself pointedly).

The logic we want would be to put `compute_precipitation_cache` somewhere in `precomputed_quantities`, instead of calling it from the tendency? And then use it from both the tendency and diagnostics?

**Comment by charleskawczynski** [comment]
> Sounds good. Apologies it's such a mess over there. It would be great to allocate some time and straighten things up (looking at myself pointedly).
> 
> The logic we want would be to put `compute_precipitation_cache` somewhere in `precomputed_quantities`, instead of calling it from the tendency? And then use it from both the tendency and diagnostics?

No problem. I'm just trying to incrementally improve on https://github.com/CliMA/ClimaCore.jl/issues/1467 for now. It's not clear to me how to best structure things, but there's definitely room for improvement.

**Pull request merged**
