### PR TITLE
Remove unused noneq

### PR DESCRIPTION
**Pull request by trontrytel**
Tmp deleting the non-eq code to speed up the integration with ClimaAtmos and debugging

### CODE REVIEW

**Comment by charleskawczynski** [comment]
Is this different from the precipitation we want to modularity? If so, LGTM, if not, then why don’t we leave it in so that we can incrementally move it to the correct place?

**Comment by trontrytel** [comment]
Different from precipitation

> Is this different from the precipitation we want to modularity? If so, LGTM, if not, then why don’t we leave it in so that we can incrementally move it to the correct place?

Different than precipitation

**Comment by haakon-e** [comment]
does this stuff also depend on any external packages that can be removed as well?

**Comment by trontrytel** [comment]
> does this stuff also depend on any external packages that can be removed as well?

Nope, no additional packages.

**Review by charleskawczynski — APPROVED** [review]

**Review by haakon-e — APPROVED** [review]

**Pull request merged**
