### PR TITLE
remove theta option for moist cases and change initial condition for baroclinic wave

### PR DESCRIPTION
**Pull request by szy21**

### CODE REVIEW

**Review by jiahe23 — APPROVED** [review]

**Comment by szy21** [comment]
bors try

**Comment by charleskawczynski** [comment]
Cache issue:
```
ERROR: LoadError: IOError: unlink("/central/scratch/esm/slurm-buildkite/climaatmos-ci/depot/cpu/compiled/v1.7/ClimaAtmos/4EXdy_Ot5m6.ji"): no such file or directory (ENOENT)
```
Let's retry, if persistent we can clear the depot.

**Pull request merged**
