### PR TITLE
Update hypdiff tendencies (follows on from 540)

### PR DESCRIPTION
**Pull request by akshaysridhar**
# PULL REQUEST

## Purpose and Content
Generalises the hyperdiffusion tendency with projection operations. 

(Provide references to any link issues. Use closes #issuenum to automatically close an open issue)
- #408 

## PR Checklist
- [x] This PR has a corresponding issue OR is linked to an SDI.
- [x] I have followed CliMA's codebase [contribution](https://clima.github.io/ClimateMachine.jl/latest/Contributing/) and [style](https://clima.github.io/ClimateMachine.jl/latest/DevDocs/CodeStyle/) guidelines OR N/A.
- [x] I have followed CliMA's [documentation policy](https://github.com/CliMA/policies/wiki/Documentation-Policy).
- [x] I have checked all issues and PRs and I certify that this PR does not duplicate an open PR.
- [x] I linted my code on my local machine prior to submission OR N/A.
- [x] Unit tests are included OR N/A.
- [x] Code used in an integration test OR N/A.
- [x] All tests ran successfully on my local machine OR N/A.
- [x] All classes, modules, and function contain docstrings OR N/A.
- [x] Documentation has been added/updated OR N/A.

### CODE REVIEW

**Comment by szy21** [comment]
@akshaysridhar do you want this to be included in the release? If so could you finish it by 5pm PT today?

**Comment by szy21** [comment]
I don't understand the vectors well enough to be able to review this. Could someone else take a look?

**Comment by akshaysridhar** [comment]
> I don't understand the vectors well enough to be able to review this. Could someone else take a look?

No worries, thanks!

**Review by simonbyrne — APPROVED** [review]

**Pull request merged**
