### PR TITLE
Try filter on moisture case

### PR DESCRIPTION
**Pull request by charleskawczynski**
This PR tries out a filter for the moist Held Suarez, I'm not sure if we've tried this, and I'm curious what happens here.

### CODE REVIEW

**Review by szy21 — APPROVED** [review]
My only major concern is that changing ρq_tot but not ρ is not physically consistent. But I think it's worth trying. Would you like to add it to the standard pipeline as well? If I remember correctly it breaks within 10 days.

**Comment by charleskawczynski** [comment]
> My only major concern is that changing ρq_tot but not ρ is not physically consistent. But I think it's worth trying. Would you like to add it to the standard pipeline as well? If I remember correctly it breaks within 10 days.

Yeah, that makes sense. Sure, I'll add a test to the regular CI.

**Comment by charleskawczynski** [comment]
It looks like applying this to the regular runs does have behavioral changes, which is interesting. I'm going to skip the regular CI for now since we're only testing.

**Pull request merged**
