### PR TITLE
Switch on 0-moment precip to moist bw

### PR DESCRIPTION
**Pull request by jiahe23**

### CODE REVIEW

**Review by szy21 — APPROVED** [review]

**Comment by jiahe23** [comment]
bors try

**Comment by trontrytel** [comment]
Is the theta in this example the dry potential temperature or liquid ice potential temperature? The source terms are written assuming it's the liquid ice potential temperature.  (Same goes for the previous PR with 0-moment micro)

**Review by trontrytel — APPROVED** [review]

**Comment by jiahe23** [comment]
> Is the theta in this example the dry potential temperature or liquid ice potential temperature? The source terms are written assuming it's the liquid ice potential temperature. (Same goes for the previous PR with 0-moment micro)

It is the liquid ice potential temperature as initialized [here](https://github.com/CliMA/ClimaAtmos.jl/blob/main/examples/hybrid/sphere/baroclinic_wave_utilities.jl#L117-L118)

**Comment by trontrytel** [comment]
> > Is the theta in this example the dry potential temperature or liquid ice potential temperature? The source terms are written assuming it's the liquid ice potential temperature. (Same goes for the previous PR with 0-moment micro)
> 
> It is the liquid ice potential temperature as initialized [here](https://github.com/CliMA/ClimaAtmos.jl/blob/main/examples/hybrid/sphere/baroclinic_wave_utilities.jl#L117-L118)

👍  Sounds good. In case we also want to support the dry theta it will be some more work on the source terms.

**Pull request merged**
