### PR TITLE
Fix 2d nhm for dry rising bubble

### LINKED ISSUE #263: Dry rising bubble is not rising
Please compare the 2dnh equations to the ClimaCore version https://github.com/CliMA/ClimaCore.jl/blob/main/examples/hybrid/plane/bubble_2d_rhotheta.jl

### PR DESCRIPTION
**Pull request by jiahe23**
Fix the equations for 2d nhm. Dry rising bubble is now rising.

It is uglier than ClimaCore bubble because we are not including flux correction or 2nd order diffusion (something to discuss for future work).

closes #263

### CODE REVIEW

**Comment by jiahe23** [comment]
plots_dry_bubble_rho_400 0
plots_dry_bubble_rho_uh_400 0
plots_dry_bubble_rho_w_400 0

rho, rho-u, rho-w at 400 sec

**Review by trontrytel — APPROVED** [review]
Awesome!

**Comment by jiahe23** [comment]
bors try

**Comment by jiahe23** [comment]
bors try

**Pull request merged**
