### PR TITLE
Turn off save to disk for GPU aquaplanet DYAMOND simulation

### PR DESCRIPTION
**Pull request by sriharshakandala**
## Purpose 
Turn off save to disk for GPU aquaplanet DYAMOND simulation

----
- [x] I have read and checked the items on the review checklist.

### CODE REVIEW

**Comment by Sbozzolo** [comment]
What's the purpose of this change?

**Comment by sriharshakandala** [comment]
> What's the purpose of this change?

The GPU pipeline is primarily for looking at the performance benchmarks. We would want to turnoff file writes for measurements! We can test IO in the general CI pipeline and/or longrun cpu/gpu pipeline!

**Comment by sriharshakandala** [comment]
We can have a separate GPU pipeline focussed on IO, if we would like to tune IO performance!

**Comment by Sbozzolo** [comment]
Implemented in #2616

**Pull request closed without merging**
