### PR TITLE
Bump patch version

### PR DESCRIPTION
**Pull request by valeriabarra**
## Purpose 
Bumps a patch release

----
- [x] I have read and checked the items on the review checklist.

### CODE REVIEW

**Review by szy21 — APPROVED** [review]
Thanks. We may want another release after #1939. I'll let you know.

**Comment by valeriabarra** [comment]
> Thanks. We may want another release after #1939. I'll let you know.

Okay, let me know. If we're tagging another one tomorrow, I can wait to update the Coupler maybe

**Comment by szy21** [comment]
> > Thanks. We may want another release after #1939. I'll let you know.
> 
> Okay, let me know. If we're tagging another one tomorrow, I can wait to update the Coupler maybe

Sounds good. That PR is not quite working yet so I don't know whether we can get it done by tomorrow. I'll know more by tomorrow noon.

**Pull request merged**
