### PR TITLE
Update GPU pipeline to use `cuda_env`

### PR DESCRIPTION
**Pull request by sriharshakandala**
## Purpose 
Update GPU pipeline to use `cuda_env`

----
- [ ] I have read and checked the items on the review checklist.

### CODE REVIEW

**Comment by Sbozzolo** [comment]
The changes in this PR were merged in https://github.com/CliMA/ClimaAtmos.jl/pull/2334, but the buildkite/gpu_pipeline is still using the examples env.

**Comment by charleskawczynski** [comment]
Should we close this, then?

**Comment by sriharshakandala** [comment]
> Should we close this, then?

I am trying the `GPU pipeline` with the latest `main` here: https://buildkite.com/clima/climaatmos-target-gpu-simulations/builds/140

**Comment by sriharshakandala** [comment]
Looks good to me!

**Pull request closed without merging**
