### PR TITLE
Adds Thomas algorithm for solving a tri-diagonal system of linear equations.

### LINKED ISSUE #648: memory allocations in tridiagonal LU factorization
The  call to [`lu!` in the linear solve](https://github.com/CliMA/ClimaAtmos.jl/blob/e7e23ba3861e80a4f0f2a798469183e57b867160/examples/hybrid/schur_complement_W.jl#L225) causes significant memory allocations. My guess is that it is caused by the allocation of the pivot array:
https://github.com/JuliaLang/julia/blob/v1.7.3/stdlib/LinearAlgebra/src/lu.jl#L500

Options:
- write our own direct tridiagonal solver. @OsKnoth might have some code?
- use [BandedMatrices.jl](https://github.com/JuliaMatrices/BandedMatrices.jl), which wraps the general LAPACK banded solvers

### PR DESCRIPTION
**Pull request by sriharshakandala**
# PULL REQUEST

## Purpose and Content
Adds Thomas algorithm for solving a tri-diagonal system of linear equations. This replaces the pre-existing `lu!` solver in `linsolve`.

## Benefits and Risks
The Thomas algorithm computes the solution in-place and eliminates memory allocations noticed in the pre-existing `lu!` solver.

## Linked Issues
(Provide references to any link issues. Use closes #issuenum to automatically close an open issue)
- Fixes #648 
- Closes #648 

## PR Checklist
- [x] This PR has a corresponding issue OR is linked to an SDI.
- [x] I have followed CliMA's codebase [contribution](https://clima.github.io/ClimateMachine.jl/latest/Contributing/) and [style](https://clima.github.io/ClimateMachine.jl/latest/DevDocs/CodeStyle/) guidelines OR N/A.
- [x] I have followed CliMA's [documentation policy](https://github.com/CliMA/policies/wiki/Documentation-Policy).
- [x] I have checked all issues and PRs and I certify that this PR does not duplicate an open PR.
- [x] I linted my code on my local machine prior to submission OR N/A.
- [x] Unit tests are included OR N/A.
- [x] Code used in an integration test OR N/A.
- [x] All tests ran successfully on my local machine OR N/A.
- [x] All classes, modules, and function contain docstrings OR N/A.
- [x] Documentation has been added/updated OR N/A.

### CODE REVIEW

**Comment by sriharshakandala** [comment]
@simonbyrne : Since this code lives in `examples/hybrid`, please advise on a good location to plug in the test.

**Review by charleskawczynski — COMMENTED** [review]
Looks good, can we add a short test in `test/` to ensure this matches against `ldiv!(lu!(A), b)`? I'm sure it's fine, but it's so nicely encapsulated that it seems like a good idea so that nobody accidentally breaks it.

**Review by charleskawczynski — APPROVED** [review]

**Comment by charleskawczynski** [comment]
Looks like this hit a depot error (and maybe even hung?). All the tests seem to pass, though, looks good!

**Pull request merged**
