### PR TITLE
Update DSS to DSS2

### PR DESCRIPTION
**Pull request by sriharshakandala**
## Purpose 
Move to new DSS implementation with optimized halo exchange.
This will replace PR https://github.com/CliMA/ClimaAtmos.jl/pull/1002

----
- [x] I have read and checked the items on the review checklist.

### CODE REVIEW

**Comment by sriharshakandala** [comment]
bors try

**Comment by simonbyrne** [comment]
maybe the simpler option is to check if the quadrature rule == `Spaces.Quadratures.GL{1}()`

**Comment by sriharshakandala** [comment]
> maybe the simpler option is to check if the quadrature rule == `Spaces.Quadratures.GL{1}()`

Yes. I tried this one and it works. I am moving the `skip_dss` entry into the `ghost_buffer` so that it only need to be checked once!

**Review by charleskawczynski — APPROVED** [review]
Code changes look fine to me

**Pull request merged**
