### PR TITLE
change upwinding default to none

### PR DESCRIPTION
**Pull request by szy21**

### CODE REVIEW

**Review by charleskawczynski — APPROVED** [review]

**Review by charleskawczynski — COMMENTED** [review]
Let's rebase/squash this first

**Comment by szy21** [comment]
> Let's rebase/squash this first

Yes for some reason I messed up the git history. It should be good now.

**Comment by charleskawczynski** [comment]
I just realized, can't we also increase the timestep for central differencing?

**Comment by szy21** [comment]
> I just realized, can't we also increase the timestep for central differencing?

We have been using 400s for central for dry cases and I remember that’s close to the largest dt we can have. For moist cases we have been using 200s, but I haven’t tried to push it with central. Jia is running some simulations, we’ll see if we can increase it.
 
 I did forget to change the dt back to 400s for the dry case with high top in the longrun though. Could you change it in your PR?

**Pull request merged**
