### PR TITLE
replacing jld2 outputs with hdf5 outputs

### PR DESCRIPTION
**Pull request by jiahe23**
Co-authored-by: Sriharsha Kandala <sriharsha.kvs@gmail.com>
Co-authored-by: Simon Byrne <simonbyrne@gmail.com>

# PULL REQUEST

## Purpose and Content
(Clearly and concisely state the purpose of this PR)

## Benefits and Risks
(State concisely the benefits to be derived from and the risks associated with this PR)

## Linked Issues
(Provide references to any link issues. Use closes #issuenum to automatically close an open issue)
- Fixes #
- Closes #

## PR Checklist
- [ ] This PR has a corresponding issue OR is linked to an SDI.
- [ ] I have followed CliMA's codebase [contribution](https://clima.github.io/ClimateMachine.jl/latest/Contributing/) and [style](https://clima.github.io/ClimateMachine.jl/latest/DevDocs/CodeStyle/) guidelines OR N/A.
- [ ] I have followed CliMA's [documentation policy](https://github.com/CliMA/policies/wiki/Documentation-Policy).
- [ ] I have checked all issues and PRs and I certify that this PR does not duplicate an open PR.
- [ ] I linted my code on my local machine prior to submission OR N/A.
- [ ] Unit tests are included OR N/A.
- [ ] Code used in an integration test OR N/A.
- [ ] All tests ran successfully on my local machine OR N/A.
- [ ] All classes, modules, and function contain docstrings OR N/A.
- [ ] Documentation has been added/updated OR N/A.

### CODE REVIEW

**Comment by simonbyrne** [comment]
Okay, MPI I/O test now passes!

**Comment by simonbyrne** [comment]
I just switched the Manifest to use the release version of ClimaCore

**Review by szy21 — APPROVED** [review]
It works for me too, thanks! @simonbyrne Do we still want to keep the jld2 option in the remap pipeline, if we are replacing jld2 with hdf5 in the output?

**Comment by charleskawczynski** [comment]
I'm working on a commit to add pieces of #672 so that this is exercised

**Comment by szy21** [comment]
> I'm working on a commit to add pieces of #672 so that this is exercised

Great, I was going to merge this now. Is it ok?

**Comment by szy21** [comment]
bors try

**Comment by charleskawczynski** [comment]
I guess so, the last force push just made my branch diverge...

**Comment by szy21** [comment]
> I guess so, the last force push just made my branch diverge...

I can wait a bit if that's better? This PR is ready I think, just let me know when we should merge it.

**Comment by charleskawczynski** [comment]
> Oh, the force push is just fixing a typo. I can wait a bit if that's better? This PR is ready I think, just let me know when we should merge it.

Let's just merge, I need to reapply all of the changes anyway. I think it'll be easier to re-apply off main.

**Pull request merged**
