### PR TITLE
upgrade to Julia 1.9

### PR DESCRIPTION
**Pull request by simonbyrne**
## Purpose 
Upgrade our examples Manifest and pipeline to Julia 1.9.

## To-do
- tag a new release of ClimaCore

## Content

----
- [x] I have read and checked the items on the review checklist.

### CODE REVIEW

**Comment by simonbyrne** [comment]
This seems to speed up initialization in some cases
 - gravity wave: 4min => 2min
 - density current 17 min => 12 min

**Comment by simonbyrne** [comment]
created longrun build https://buildkite.com/clima/climaatmos-longruns/builds/1145

**Review by szy21 — APPROVED** [review]

**Comment by szy21** [comment]
There seems to be some issue with the MPI job (it wouldn't start)

**Comment by szy21** [comment]
@Sbozzolo This is the PR

**Comment by Sbozzolo** [comment]
> @Sbozzolo This is the PR

Yes, I am looking into it.

**Comment by Sbozzolo** [comment]
I tracked it down to the new flag we added `slurm_mem_per_cpu: 8G`. 

This [minimal build](https://buildkite.com/clima/climaatmos-ci/builds/12474#018a3d8b-e729-4ad6-ada2-d86803e93dd7) starts. 

I also verified that manually submitting a script with that option works (after you fiddle around with MPI/HDF5). 

```
#!/bin/bash

#SBATCH --ntasks=2
#SBATCH --mem-per-cpu=8G
#SBATCH --job-name=MyTest
#SBATCH --time=0:23:00

module purge
module load julia/1.9.2 cuda/11.8 ucx/1.14.1_cuda-11.8 openmpi/4.1.5_cuda-11.8 hdf5/1.12.2-ompi415 nsight-systems/2023.2.1

export CLIMACORE_DISTRIBUTED="MPI"
export CLIMACOMMS_CONTEXT="MPI"

cd ClimaAtmos.jl

julia -e 'using Pkg; Pkg.add("MPIPreferences"); using MPIPreferences; use_system_binary()'
julia --project=examples -e 'using Pkg; Pkg.build("MPI")'
julia --project=examples -e 'using Pkg; Pkg.build("HDF5")'
julia --project=examples -e 'using Pkg; Pkg.API.precompile()'
srun julia --color=yes --project=examples examples/hybrid/driver.jl --config_file config/mpi_configs/mpi_make_restart.yml
```

So, I am guessing that buildkite-slurm bridge is not properly translating the option.

**Comment by szy21** [comment]
Great, thanks! If all other ci jobs work, I am happy to get this in and remove the `slurm_mem_per_cpu` flag. We can also wait until Simon comes back - up to you.

**Comment by simonbyrne** [comment]
Ah, I think it's because we set `--mem` (globally for all jobs), and that must be incompatible with `--mem-per-cpu`

**Comment by Sbozzolo** [comment]
Good point, I was running into the same problem when writing my own SLURM
script.

It has to be it!

**Pull request merged**
