### PR TITLE
Fix call to thermo state

### PR DESCRIPTION
**Pull request by charleskawczynski**
This PR fixes a call to create a thermodynamic state at the surface

### CODE REVIEW

**Review by trontrytel — APPROVED** [review]

**Comment by charleskawczynski** [comment]
Not that this is correct, but I printed the created thermo state (in [this build](https://buildkite.com/clima/climaatmos-ci/builds/5699#018491d8-c851-4d75-83a6-f9ca100bee6d)) to find out what temperature that we're actually using, and the result seems to be:

```julia
    # Tsurface::FT = 299.8
    Tsurface::FT = 301.10523249821375

    # For Rico we provide values of transfer coefficients
    ts = TD.PhaseEquil_pTq(thermo_params, p_f_surf, Tsurface, FT(0)) # TODO: is this correct?
    qsurface = TD.q_vap_saturation(thermo_params, ts)
    ts_sfc = TD.PhaseEquil_pθq(thermo_params, p_f_surf, Tsurface, qsurface)
    @show TD.liquid_ice_pottemp(thermo_params, ts_sfc)
    @show TD.air_temperature(thermo_params, ts_sfc)
    error("Done")

TD.liquid_ice_pottemp(thermo_params, ts_sfc) = 299.8
TD.air_temperature(thermo_params, ts_sfc) = 301.10523249821375
ERROR: LoadError: Done
```
Let's see what happens...

**Comment by charleskawczynski** [comment]
@trontrytel, results from the last commit look fine to me, maybe we can open an issue about matching ICs from the paper? (perhaps this can be tuned once we have the ML pieces ready?)

**Comment by trontrytel** [comment]
> @trontrytel, results from the last commit look fine to me, maybe we can open an issue about matching ICs from the paper? (perhaps this can be tuned once we have the ML pieces ready?)

💯 I agree. I'm sure those could be calibrated away, once we have the ML part hooked in here

**Pull request merged**
