### PR TITLE
add compat for ClimaCore

### PR DESCRIPTION
**Pull request by szy21**
## Purpose 

We replaced `column_mapreduce!` with `column_reduce!` in this PR to be compatible with ClimaCore v0.14.11: https://github.com/CliMA/ClimaAtmos.jl/pull/3233

## Content

----
- [ ] I have read and checked the items on the review checklist.

### CODE REVIEW

**Comment by Sbozzolo** [comment]
Can you add a link to one of the commits that start requiring ClimaCore 0.14.11 ?

**Comment by szy21** [comment]
> Can you add a link to one of the commits that start requiring ClimaCore 0.14.11 ?

I added it in the description of the PR. Should I add it somewhere else?

**Comment by Sbozzolo** [comment]
> > Can you add a link to one of the commits that start requiring ClimaCore 0.14.11 ?
> 
> I added it in the description of the PR. Should I add it somewhere else?

No, it's good.

**Review by Sbozzolo — APPROVED** [review]

**Comment by szy21** [comment]
not sure why the regression test failed...

**Comment by szy21** [comment]
cc @charleskawczynski

**Pull request merged**
