### PR TITLE
Fix precipitation test

### PR DESCRIPTION
**Pull request by trontrytel**
@charleskawczynski , @dennisYatunin - I think this should work better with this PR https://github.com/CliMA/ClimaAtmos.jl/pull/2580

### CODE REVIEW

**Review by charleskawczynski — APPROVED** [review]
Code changes look fine to me, we'll need to let #2619 through first, to fix CI

**Comment by szy21** [comment]
@trontrytel need to fix the tiny change in allocation :(

**Comment by trontrytel** [comment]
Increasing by `1.0000088187627407`

**Comment by charleskawczynski** [comment]
🤷🏻, I think we need to fix inference in the diagnostics.

**Pull request merged**
