### PR TITLE
As/callback interface

### PR DESCRIPTION
**Pull request by akshaysridhar**
Provides simple callback interface for use with DiffEqBase (JLD2 output). 
Support for `PeriodicCallback` included. Future iterations will consider existing Oceananigans features and unify interfaces.

### CODE REVIEW

**Comment by glwagner** [comment]
`Oceananigans.Simulation` has a callback infrastructure, so we ultimately won't need a separate implementation here. What's the purpose of this PR?

**Comment by akshaysridhar** [comment]
> `Oceananigans.Simulation` has a callback infrastructure, so we ultimately won't need a separate implementation here. What's the purpose of this PR?

Intent here is to merge ClimaAtmos interfaces with Oceananigans design ideas and provide convenience functions for end-users; (starting with common diagnostic outputs)

**Comment by glwagner** [comment]
> > `Oceananigans.Simulation` has a callback infrastructure, so we ultimately won't need a separate implementation here. What's the purpose of this PR?
> 
> Intent here is to merge ClimaAtmos interfaces with Oceananigans design ideas and provide convenience functions for end-users; (starting with common diagnostic outputs)

Okay, great.

Oceananigans.Simulation has two lists of user-facing callback-like objects:

1. `Simulation.callbacks`, an `OrderedDict` of `Oceananigans.Callback` and
2. `Simulation.output_writers`, an `OrderedDict` of `Oceananigans.OutputWriters` that write output to disk.

`Oceananigans.Callback` is a relatively recent feature that should be used to do things like implement adaptive time-stepping or other discrete updates to the model state within the time-stepping loop.

`Oceananigans.OutputWriters` is the canonical way to write output to disk. There are three types of output writers: a `Checkpointer`, `JLD2OutputWriter` and `NetCDFOutputWriter`.

The last two can output arbitrary data (NetCDF must be scalars or arrays, JLD2 can output any julia object). To specify output, users provide lists of name, value pairs (either `NamedTuple` or `Dict`). The "values" of these lists are either `AbstractField`, or arbitrary functions.

**Review by bischtob — APPROVED** [review]
Made a few minor modifications. This is ready after it passed checks. Feel free to squash + rebase + r+

**Comment by akshaysridhar** [comment]
bors try

**Pull request merged**
