### PR TITLE
Update ClimaCore, switch to using tuples instead of Refs

### PR DESCRIPTION
**Pull request by simonbyrne**
## Purpose 
Test out latest ClimaCore, including memory fixes (https://github.com/CliMA/ClimaCore.jl/pull/1113)

## Content

----
- [ ] I have read and checked the items on the review checklist.

### CODE REVIEW

**Comment by simonbyrne** [comment]
This is blocked by https://github.com/CliMA/ClimaCore.jl/pull/1124

**Comment by simonbyrne** [comment]
Need to track down the source of allocations: https://buildkite.com/clima/climaatmos-ci/builds/7041#01863c95-215c-4179-826e-6fa4667e8dd8

**Comment by simonbyrne** [comment]
Looks like EDMF is causing problems, will need to look into it

**Comment by simonbyrne** [comment]
Okay, I think this is ready once we tag a new ClimaCore.

**Review by szy21 — APPROVED** [review]
Looks good, thanks! Why does the update (memory fix) increase the allocation for `flame_perf_target_edmf` though?

**Comment by simonbyrne** [comment]
I'm not sure: I think it might be the same issue @akshaysridhar was seeing, I just used a higher threshold.

**Comment by szy21** [comment]
The difference Akshay saw is much smaller I think, less than 1e-5？

**Comment by simonbyrne** [comment]
@szy21 not sure what is going on with the mse tables?

**Comment by akshaysridhar** [comment]
> The difference Akshay saw is much smaller I think, less than 1e-5？

The magnitude of this is one aspect (I guess this informs our allocation safety-buffer size), the issue was additionally that the allocation change result was not deterministic.

**Comment by simonbyrne** [comment]
what's the fix for the mse tables stuff?

**Comment by szy21** [comment]
I haven’t looked at the ci. @simonbyrne do you expect behavior change?

**Comment by szy21** [comment]
The results look fine to me. @simonbyrne if you expect behavior change for this PR, and think the allocation change is ok, I can fix the mse and merge it.

**Comment by simonbyrne** [comment]
no, i don't expect any behavior change

**Comment by szy21** [comment]
> no, i don't expect any behavior change

Oh, but the mse table suggests that there are behavior changes?

**Comment by simonbyrne** [comment]
yeah, i'm not sure what is going on there. Has something changed, because the last test I ran passed: https://buildkite.com/clima/climaatmos-ci/builds/7670#01869ef2-cb56-4b5e-ac81-6f22081d07ae

**Comment by szy21** [comment]
The only PRs that changes mse between Wednesday and now are #1398 and #1327 I think

**Comment by akshaysridhar** [comment]
> yeah, i'm not sure what is going on there. Has something changed, because the last test I ran passed: https://buildkite.com/clima/climaatmos-ci/builds/7670#01869ef2-cb56-4b5e-ac81-6f22081d07ae

The `ref_counter` was bumped from 73->74 in the last build (linked above) - this means the system treats it as a self-reference and that would pass the CI build right ?

**Comment by simonbyrne** [comment]
okay, i started a longruns build: https://buildkite.com/clima/climaatmos-longruns/builds/838

**Comment by szy21** [comment]
The results look fine to me.

[longrun_hs_rhoe_highres_hightop](https://buildkite.com/organizations/clima/pipelines/climaatmos-longruns/builds/838/jobs/0186aa17-7de2-4d51-8230-0f855c9b186e/artifacts/0186adf8-a307-43d2-b111-1cb7cb16bd0b)
image
image

[longrun_hs_rhoe_equilmoist_highres_hightop_rayleigh30e3](https://buildkite.com/organizations/clima/pipelines/climaatmos-longruns/builds/838/jobs/0186aa17-7dee-4406-9f34-c3dcce9d0e0e/artifacts/0186aeb2-0faa-4383-827f-d6fd4cdebec9)
image
image

**Pull request merged**
