### PR TITLE
Check in examples Manifest.toml

### PR DESCRIPTION
**Pull request by charleskawczynski**

### CODE REVIEW

**Comment by jiahe23** [comment]
need to delete Manifest from gitignore

**Comment by charleskawczynski** [comment]
I was thinking of leaving `Manifest.toml` in the .gitignore, so that we continue ignoring the one in the package directory

**Comment by charleskawczynski** [comment]
We can manually add the other ones.

**Comment by jiahe23** [comment]
bors try

**Comment by charleskawczynski** [comment]
We'll still skip the Manifest in the test directory, since it seems that this causes issues with running `Pkg.test` (and codecov).

**Pull request merged**
