### PR TITLE
Fix moist baro wave

### PR DESCRIPTION
**Pull request by charleskawczynski**
This PR fixes the moist baro wave

### CODE REVIEW

**Comment by charleskawczynski** [comment]
@szy21, can you try edmf on the gpu once this merges?

**Comment by szy21** [comment]
Sounds good. Do I just follow the example in buildkite?

**Comment by charleskawczynski** [comment]
> Sounds good. Do I just follow the example in buildkite?

Yeah, you should be able to just use the edmf example and add GPU resources (`--device = "auto"` by default, so it can have the exact same CL model flags)

**Comment by szy21** [comment]
I think it's merged, but for some reason this PR is not closed.

**Comment by charleskawczynski** [comment]
Yeah, that's a bit odd. closing.

**Pull request closed without merging**
