### PR TITLE
Remove `p_ivp`

### PR DESCRIPTION
**Pull request by charleskawczynski**
This PR removes `p_ivp`, and instead relies on the pressure defined in `log_pressure_profile` (we're currently re-defining pressure).

I think if we were to merge this, that #1330 would not work.

### CODE REVIEW

**Comment by trontrytel** [comment]
I don't think thats correct? We need to solve the p_ivp as defined per each paper based test case

**Comment by trontrytel** [comment]
I think that what is done in the log_pressure_profile assumes T=constant going from the surface up. This is not a good profile from the paper cases. We should be using the p_ivp solution that uses the temperature and humidity profiles prescribed in each case.

**Comment by charleskawczynski** [comment]
Right, this is basically reverting [724](https://github.com/CliMA/ClimaAtmos.jl/pull/724), which had extensive review. I think the `p_ivp` is different from the pressure log function because the moisture profile in the case is used as the reference moisture profile. Closing.

**Comment by charleskawczynski** [comment]
We probably should have removed the log pressure fun in #724, though, since it introduced redefining the pressure. Removing it could be incorporated into #1330.

**Pull request closed without merging**
