### PR TITLE
Move TurbulenceConvectionUtils to src

### PR DESCRIPTION
**Pull request by charleskawczynski**
This PR moves TurbulenceConvectionUtils into src. To help push along #1383

Perhaps we want to distribute these functions into different places in src? Suggestions?

Co-authored by @jiahe23

### CODE REVIEW

**Comment by jiahe23** [comment]
In the end, we would like to have `dycore_equations`, `physical_parameterizations`, `shared_utils` in the src. EDMF will sit in the dycore folder. We have moved as many parameterizations as we can to the parameterization folder for now, but haven't touch the dycore part yet (to avoid to many conflicts with the ongoing developments/debugging). 

I think for now it is ok to move the TCUtils to the TC folder and later on move the entire TC into dycore folder once it's ready.

**Comment by charleskawczynski** [comment]
> In the end, we would like to have `dycore_equations`, `physical_parameterizations`, `shared_utils` in the src. EDMF will sit in the dycore folder. We have moved as many parameterizations as we can to the parameterization folder for now, but haven't touch the dycore part yet (to avoid to many conflicts with the ongoing developments/debugging).
> 
> I think for now it is ok to move the TCUtils to the TC folder and later on move the entire TC into dycore folder once it's ready.

That all sounds good, I don't mind waiting if that's smoother

**Pull request merged**
