### PR TITLE
Update dependencies, switch to ClimaParams

### PR DESCRIPTION
**Pull request by nefrathenrici**
Compat changes:
- Adapt 3.7 -> 4
- CLIMAParameters 0.9 -> ClimaParams 0.10
- CloudMicrophysics =0.17 -> 0.18
- Insolation =0.9.1 -> 0.9.2
- RRTMGP 0.12 -> 0.13.1
- SurfaceFluxes 0.9 -> 0.11
- Thermodynamics =0.12.3 -> 0.12.4
- I tried to free NCDatasets, but the diagnostics perf job doubled its allocations

Other changes
- RRTMGPInterface updated
- Manifests updated to 1.10.2
- All instances of CLIMAParameters changes to ClimaParams
- Flame GPU job allocations lowered by from 4.3e6 to 1.6e6, other allocation counts reformatted for readability

### CODE REVIEW

**Comment by charleskawczynski** [comment]
Let’s rebase this after #2723

**Comment by szy21** [comment]
We should be able to remove the zenith angle check with the latest RRTMGP release. Removing it will change MSE though, so up to you whether you want to do it in this PR.

**Comment by nefrathenrici** [comment]
@szy21 Thank you for mentioning it! I can do it in the next PR, this is changing a lot of packages but doesn't have simulation output changes.

**Review by szy21 — APPROVED** [review]
Thanks!

**Comment by Sbozzolo** [comment]
If you can reproduce the problem with NCDatasets we should open an issue.

**Pull request merged**
