### PR TITLE
update dependencies and bump patch version

### PR DESCRIPTION
**Pull request by szy21**
## Content

----
- [ ] I have read and checked the items on the review checklist.

### CODE REVIEW

**Comment by szy21** [comment]
Calibration is pinned to ClimaAtmos v0.27.2 - What should I do about it?

**Comment by AlexisRenchon** [comment]
> Calibration is pinned to ClimaAtmos v0.27.2 - What should I do about it?

I am not sure...

**Review by AlexisRenchon — APPROVED** [review]

**Comment by szy21** [comment]
> > Calibration is pinned to ClimaAtmos v0.27.2 - What should I do about it?
> 
> I am not sure...

I will not change it then...:)

**Comment by Sbozzolo** [comment]
> Calibration is pinned to ClimaAtmos v0.27.2 - What should I do about it?

You should not update its Manifest, otherwise we cannot guarantee anything about reproduciability.

**Comment by AlexisRenchon** [comment]
maybe Calibration Project could have compat for ClimaAtmos
calibration/test/Project.toml

**Review by Sbozzolo — APPROVED** [review]

**Pull request merged**
