### PR TITLE
Clean up compat entries and update deps

### LINKED ISSUE #1971: Clean up compat entries
We have a lot of duplicated compat entries between the top-level package directory `ClimaAtmos.jl/` and its subdirectories. These can cause clashes/incompatibilities and create a maintenance burden. 

**Solution proposed:**
Remove duplicated compat entries in subdirectories.

### PR DESCRIPTION
**Pull request by valeriabarra**
## Purpose 
The purpose of this PR is two-fold: 
* Clean-up compat entries, by adding missing ones and/or removing duplicated ones
* Update dependencies in all environments

Closes #1971 

## Content
- Solution implemented:
    - [x] Updated compat entries by adding missing ones, using `CompatDevTools`
    - [x] Removed duplicated compat entries in subdirectories 
    - [x] Updated all dependencies using `julia ./.dev/up_deps.jl`

----
- [x] I have read and checked the items on the review checklist.

### CODE REVIEW

**Comment by valeriabarra** [comment]
CI passes. 
Can I have a review please? 
cc: @simonbyrne , @sriharshakandala ?

**Comment by sriharshakandala** [comment]
Looks good to me!

**Comment by valeriabarra** [comment]
> Looks good to me!

Great. Thanks. When approved, I'll merge it.

**Review by sriharshakandala — APPROVED** [review]

**Pull request merged**
