### PR TITLE
Explicit specification of time limits for newly added jobs

### PR DESCRIPTION
**Pull request by akshaysridhar**
Update buildkite pipeline (longrun) to add explicit walltime-limit (1 day). 
Fix typo in clearsky longrun build.

### CODE REVIEW

**Comment by akshaysridhar** [comment]
Testing here: https://buildkite.com/clima/climaatmos-longruns/builds/1164

**Review by szy21 — APPROVED** [review]
Thanks!

**Comment by szy21** [comment]
@akshaysridhar there is also a typo in one config file name. I just changed it and pushed a commit.

**Comment by szy21** [comment]
The simulations are running. Feel free to merge it.

**Pull request merged**
