### PR TITLE
use plots.jl log axis

### PR DESCRIPTION
**Pull request by simonbyrne**
## Purpose 

This uses the `x/yaxis=:log` option, which gives nicer output:

high-resolution_Scaling_efficiency_vs_ncols
high-resolution_Scaling_efficiency
high-resolution_Scaling
high-resolution_sypd

Follow up to #1067 
## Content

----
- [x] I have read and checked the items on the review checklist.

### CODE REVIEW

**Comment by simonbyrne** [comment]
Running on https://buildkite.com/clima/climaatmos-scaling/builds/368

**Comment by charleskawczynski** [comment]
Ah, crud, sorry! I moved this into `ClimaAtmos.jl/post_processing/`!

**Pull request merged**
