### PR TITLE
Add julia 1.11-beta to lookahead and add dependabot

### PR DESCRIPTION
**Pull request by Sbozzolo**
See if we can catch some problems earlier than later.

### CODE REVIEW

**Comment by Sbozzolo** [comment]
https://github.com/CliMA/ClimaAtmos.jl/actions/runs/8765896794/job/24057894026?pr=2931

AtmosConfig cannot be inferred/compiled in Julia 1.11-beta1

**Review by charleskawczynski — COMMENTED** [review]
Looks great, I'd like to see the error, but I'm running into cuda compilation issues.

Maybe we can remove CUDA as a direct dependency first, as none of our GHA runners will run on gpus.

**Comment by Sbozzolo** [comment]
When I tried on my laptop, compilation would just hang with no errors.

Hopefully things will improve in the next betas

**Comment by charleskawczynski** [comment]
I’m happy to merge this with soft-fail after rebasing

**Review by charleskawczynski — APPROVED** [review]

**Pull request merged**
