### PR TITLE
Restore OutputPathGenerator

### LINKED ISSUE #3048: Re-introduce `OutputPathGenerator`
As reported by @charleskawczynski and @trontrytel in https://github.com/CliMA/ClimaDiagnostics.jl/issues/56
and by @akshaysridhar in https://github.com/CliMA/ClimaDiagnostics.jl/issues/55

> I don't have a reproducer for this, so I'm not sure what causes this issue, but here is an error I ran into with @trontrytel

> ERROR: LoadError: incompatible dimensions for orog
Stacktrace:
  [1] error(s::String)
    @ Base .\error.jl:35
  [2] write_field!(writer::ClimaDiagnostics.Writers.NetCDFWriter{…}, field::ClimaCore.Fields.Field{…}, diagnostic::ClimaDiagnostics.ScheduledDiagnostics.ScheduledDiagnostic{…}, u::ClimaCore.Fields.FieldVector{…}, p::ClimaAtmos.AtmosCache{…}, t::Float32)
    @ ClimaDiagnostics.Writers C:\Users\kawcz\.julia\packages\ClimaDiagnostics\gzst4\src\netcdf_writer.jl:330
  [3] ClimaDiagnostics.DiagnosticsHandler(scheduled_diagnostics::Vector{…}, Y::ClimaCore.Fields.FieldVector{…}, p::ClimaAtmos.AtmosCache{…}, t::Float32; dt::Float32)
    @ ClimaDiagnostics C:\Users\kawcz\.julia\packages\ClimaDiagnostics\gzst4\src\clima_diagnostics.jl:95
  [4] DiagnosticsHandler
    @ C:\Users\kawcz\.julia\packages\ClimaDiagnostics\gzst4\src\clima_diagnostics.jl:56 [inlined]
  [5] IntegratorWithDiagnostics(integrator::ClimaTimeSteppers.DistributedODEIntegrator{…}, scheduled_diagnostics::Vector{…})
    @ ClimaDiagnostics C:\Users\kawcz\.julia\packages\ClimaDiagnostics\gzst4\src\clima_diagnostics.jl:280
  [6] macro expansion
    @ C:\dev\CliMA\ClimaAtmos.jl\src\solver\type_getters.jl:709 [inlined]
  [7] macro expansion
    @ .\timing.jl:503 [inlined]
  [8] macro expansion
    @ C:\dev\CliMA\ClimaAtmos.jl\src\utils\utilities.jl:331 [inlined]
  [9] get_simulation(config::ClimaAtmos.AtmosConfig{…})
    @ ClimaAtmos C:\dev\CliMA\ClimaAtmos.jl\src\solver\type_getters.jl:708
 [10] top-level scope
    @ C:\dev\CliMA\ClimaAtmos.jl\examples\hybrid\driver.jl:15
 [11] include(fname::String)
    @ Base.MainInclude .\client.jl:489
 [12] top-level scope
    @ REPL[3]:1
in expression starting at C:\dev\CliMA\ClimaAtmos.jl\examples\hybrid\driver.jl:15
Some type information was truncated. Use `show(err)` to see complete types.

The root issue:
> NetCDF files come with defined dimensions that you are not allowed to change. If you re-run a simulation with the same output_dir and change anything about it, you will end up with incompatible NetCDF files. This happens very frequently when developing in the REPL, so the solution was that every time a new Simulation is created, a new folder is also created. Previous folders are retained to ensure that one can still inspect the output there. This is implemented in `OutputPathGenerator`.

### PR DESCRIPTION
**Pull request by Sbozzolo**
This commit restores OutputPathGenerator for directory managment and adds a new option, `output_dir_style` to control its behavior.

By default OutputPathGenerator uses the ActiveLinkStyle, meaning that new subfolders are created within `output_dir` every time a Simulation object is created. The most recent output can always be found in `output_dir/output_active`. This style preserves existing data, and running multiple times on the same `output_dir` will lead to a list of `output_dir/output_0123` folders with the data for each separate run.

The other style currently implemented is `RemovePreexisting`. With this style, if `output_dir` already exists, it will be overwritten with the new one.

Closes #3048

### CODE REVIEW

**Review by charleskawczynski — COMMENTED** [review]
I'll add some workflow tests, and then we can rebase and make sure that this solution cooperates with those workflows. It's EOD for me today, so I'll add them Monday.

**Comment by Sbozzolo** [comment]
I thought of a very simple solution that should satisfy everyone.

In https://github.com/CliMA/ClimaUtilities.jl/pull/63, I slightly changed the behavior of `OutputPathGenerator`. Instead of returning `output_active`, it returns the path to the newly created folder. Links are still being created and managed. This means that:
- ClimaAtmos will see a normal folders with incremented counters
- Users will still be able to assume and use the fact that `output_active` points to the most recent data generated (which is very useful when `rsycing` data from the cluster to local computers or running analysis scripts)

**Review by charleskawczynski — APPROVED** [review]
Let's instead give this a try and I'll open an issue if I run into any problems

**Comment by Sbozzolo** [comment]
> Let's instead give this a try and I'll open an issue if I run into any problems

Okay, I'll merge the PR in ClimaUtilities (if you can please approve it) and make a new release before merging this.

**Pull request merged**
