### PR TITLE
Update kinetic energy computation

### LINKED ISSUE #1293: Implement the function to calculate kinetic energy from DD

### PR DESCRIPTION
**Pull request by akshaysridhar**
Updates the expression for kinetic energy computation using covariant velocity components.
Updates the corresponding equations in online documentation. 
Decreases timesteps in EDMF cases (BOMEX-JFNK, BOMEX-compressible and Soares). 

Closes #1293

### CODE REVIEW

**Review by Zhengyu-Huang — APPROVED** [review]
Great work! The implementation is the same as the design doc!
Please trigger the long run test, if the test passes, merge the PR!

**Comment by akshaysridhar** [comment]
Longrun-Buildkite Output
**Zonal Velocity**
mean_u_sigma
**Potential Temperature**
mean_pottemp
**Temperature**
mean_temp_sigma

**Comment by bischtob** [comment]
@akshaysridhar, do we have longruns for some moist sims as well?

**Comment by akshaysridhar** [comment]
**_EquilMoist-Held-Suarez_** (No Limiter, ARS Timestepper) - Longrun-Buildkite Output
**Zonal Velocity**
mean_u_sigma
**Potential Temperature**
mean_pottemp_sigma
**Temperature**
mean_temp_sigma
**Specific Moisture**
mean_qt_sigma

400 day simulation; discarding first 200 days of spin-up time in averaged plots. 

cc @bischtob @szy21

**Comment by szy21** [comment]
Looks good to me. Let's get this in if all the tests (ARS, no topography) passed and focus on the box test cases with topography.

**Comment by akshaysridhar** [comment]
> Looks good to me. Let's get this in if all the tests (ARS, no topography) passed and focus on the box test cases with topography.

Noted, thanks. I'll post the aquaplanet results shortly - the `targeted` cases appear to pass (see https://github.com/CliMA/ClimaAtmos.jl/pull/1398#issuecomment-1452317905). Re-starting the SSP case appears to work, 1 of 2 cases is currently running (it appears to drop out due to memory issues depending on the specific nodes allocated) - the second aquaplanet clearsky case has output for `380 days` following which there appears to have been a node failure.

**Comment by akshaysridhar** [comment]
**Aquaplanet-EquilMoist-Clearsky_** (No Limiter, ARS Timestepper) - Longrun-Buildkite Output

Zonal Velocity
mean_u_sigma

Potential Temperature
mean_pottemp_sigma

Temperature 
mean_temp_sigma

Total Specific Moisture
mean_qt_sigma

**Comment by akshaysridhar** [comment]
**_Aquaplanet-EquilMoist-Clearsky-Hightop_** - Longrun-Buildkite Output

**Zonal Velocity**
mean_u_sigma

**Potential Temperature**
mean_pottemp_sigma

**Temperature**
mean_temp_sigma

**Total Specific Moisture**
mean_qt_sigma

380 day simulation; discarded first 200days of spin-up time in averaged plots.

**Comment by szy21** [comment]
Did it break at day 380, or it runs out of time?

**Comment by akshaysridhar** [comment]
> Did it break at day 380, or it runs out of time?

Based on the output : `Exited with status -1 (agent lost)`, and the runtime of `1d0h` it's a timeout issue. The SLURM setup has the following - `TimeLimit=1-00:00:00 `. Nevertheless, for what is available (380days) , the plot is included above.

**Review by bischtob — APPROVED** [review]
I think based on longruns so far, this seems mergable :).

**Comment by akshaysridhar** [comment]
This has been a curious buildkite outcome - with different staging builds (following the successful one listed here: https://buildkite.com/clima/climaatmos-ci/builds/7695#0186a486-ed56-4d63-b4d4-9bb2d8d299fd resulting in varying allocation counts (usually difference of _O(1e-5, 1e-6)_ ), see the intermediate failed bors builds for reference. Flagging here as a note for future builds.

**Pull request merged**
