### PR TITLE
Update manifest files

### PR DESCRIPTION
**Pull request by charleskawczynski**
This PR updates the dependencies, which includes https://github.com/CliMA/ClimaCore.jl/pull/1392

### CODE REVIEW

**Comment by charleskawczynski** [comment]
Can someone (@nefrathenrici, or @valeriabarra, or @juliasloan25) review the results in here to make sure the physical results still look okay?

**Comment by valeriabarra** [comment]
The BW and HS tests have no difference at all (when compared to the results on `main`). The aquaplanet test has some small differences. But I am not the best person to tell if those are significant or not. Perhaps @szy21 ?

**Comment by szy21** [comment]
The aquaplanet looks fine to me.

**Pull request merged**
