### PR TITLE
Add h_tot to precomputed quantities

### PR DESCRIPTION
**Pull request by dennisYatunin**
## Purpose 

This PR is split off from #1660, per @szy21's request. It adds `ᶜh_tot` (as well as `ᶜh_totʲs`) to the precomputed quantities, so that we do not need to keep recomputing that value. It also adds the helper function `g³³_field` to `utilities.jl`, and it fixes a random typo in `subsidence.jl`.

----
- [x] I have read and checked the items on the review checklist.

### CODE REVIEW

**Review by szy21 — APPROVED** [review]
LGTM, thanks! You can use the `total_specific_enthalpy` in Thermodynamics.

**Comment by dennisYatunin** [comment]
bors cancel

**Comment by dennisYatunin** [comment]
bors cancel

**Pull request merged**
