### PR TITLE
Fix 3355

### LINKED ISSUE #3355: insolation_tuple is not correctly set for boxes/columns
https://github.com/CliMA/ClimaAtmos.jl/blob/aedb9984dd95a53a199f2c223d8b3f664f7d33bc/src/callbacks/callbacks.jl#L325

this update is not in-place, so `p.radiation.insolation_tuple` does not get update.

### PR DESCRIPTION
**Pull request by charleskawczynski**
Closes #3355.

### CODE REVIEW

**Review by szy21 — APPROVED** [review]

**Comment by Sbozzolo** [comment]
I tried that, but it doesn't work. I'll paste the error tomorrow

**Comment by charleskawczynski** [comment]
> I tried that, but it doesn't work. I'll paste the error tomorrow

It looks like it's the next line that's breaking, interesting.

**Comment by charleskawczynski** [comment]
Ah, that's the only block that it's used, so this shouldn't actually change the behavior anywhere. Also, the existing form is technically a bit more efficient since `insolation_tuple` is not spatially varying in that case. We could micro-optimize the cache for this, but I think it's still better to be safe for now and still update `insolation_tuple` in the cache, in case it is used in the future (or in development branches).

**Comment by Sbozzolo** [comment]
> Ah, that's the only block that it's used, so this shouldn't actually change the behavior anywhere. Also, the existing form is technically a bit more efficient since `insolation_tuple` is not spatially varying in that case. We could micro-optimize the cache for this, but I think it's still better to be safe for now and still update `insolation_tuple` in the cache, in case it is used in the future (or in development branches).

I agree, even if it is used only here, we should be consistent and keep it updated. It is counterintuitive that in some cases `p.radiation.insolation_tuple` is updated and valid, but in other cases is uninitialized.

**Pull request closed without merging**
