### PR TITLE
Port box mountain wave test to ClimaAtmos

### PR DESCRIPTION
**Pull request by akshaysridhar**
## Purpose 
Linked issue: #1347 

Moves Agnesi-Mountain and Density-Current 2D problems to ClimaAtmos. Introduces a simple ClimaCoreMakie post-proc function to handle 2D extruded discretizations. Adds `init_cond` CLI-option to generate initial conditions for 2D configurations.

### CODE REVIEW

**Review by bischtob — COMMENTED** [review]
@akshaysridhar, we can just post some plots here to see when we are happy?

**Comment by bischtob** [comment]
@akshaysridhar, can you post plots here?

**Comment by akshaysridhar** [comment]
Horz_Vel_Agnesi_Lin_p1

**Comment by akshaysridhar** [comment]
Agnesi - Vertical Velocity (With Hyperdiffusion Enabled) 
testimage_w

Agnesi - Vertical Velocity (With Hyperdiffusion Disabled) 
testimage_w

**Comment by akshaysridhar** [comment]
Case: Steep Agnesi Peak (1km)
Resolution: 1125m x 667m
Failure mode: 
U_Instability

W_Instability

**Review by Zhengyu-Huang — APPROVED** [review]
The PR looks great, thank you for the effort!

Please try increasing the sponge viscosity to stabilize the mountain test with large height, and report the results

**Comment by akshaysridhar** [comment]
Schar mountain [40km wavelength, 50km half-width]

Vertical Velocity
testimage_w_full

Horizontal-Velocity
testimage_u_full

Virtual Pottemp
testimage_pottemp

Total Energy
testimage_e_tot

**Pull request closed without merging**
