### PR TITLE
Rename w to u_3

### PR DESCRIPTION
**Pull request by szy21**
## Purpose 

Rename w to u_3 except for the old EDMF

## To-do

- [ ] update mse table

## Content

----
- [ ] I have read and checked the items on the review checklist.

### CODE REVIEW

**Comment by simonbyrne** [comment]
Could we call it `u_v` so it matches the horizontal (`u_h`)?

**Comment by simonbyrne** [comment]
in the docs, i distinguish between them: $u_3$ is the 3rd covariant component, $\boldsymbol{u}_v = \boldsymbol{e}^3 u_3$ is a vector

**Comment by szy21** [comment]
> Could we call it `u_v` so it matches the horizontal (`u_h`)?

We talked about this. Some people don't like `u_v` because v is usually for meridional velocity. We could consider renaming `u_h` to `u_12` (in a separate PR) though.

**Comment by simonbyrne** [comment]
that's fair. We could be more descriptive (`u_vert` / `u_horz`)?

**Comment by simonbyrne** [comment]
but I'm fine with this change: it is an improvement on `w`.

**Review by charleskawczynski — APPROVED** [review]
The diff looks good to me

**Review by trontrytel — APPROVED** [review]

**Pull request merged**
