### PR TITLE
surface condition and edmf hack to meet Aug 7 deadline

### PR DESCRIPTION
**Pull request by szy21**
## Purpose 

Sorry :(
We are not really sorry
-- Zhaoyi, Dennis, Lenka

@dennisYatunin will take this on

## Content

----
- [ ] I have read and checked the items on the review checklist.

### CODE REVIEW

**Comment by szy21** [comment]
@dennisYatunin Could you add the test and merge it today?

**Comment by szy21** [comment]
Actually another thing: I am not sure if this hack works for restarting a simulation (as t won't be zero), so maybe it's worth checking.

**Comment by LenkaNovak** [comment]
usually `reinit!` allows you to deal with that but def worth checking before merging...

**Comment by LenkaNovak** [comment]
trying this branch locally seems to work, but the `@info here` needs to be removed lol

**Comment by szy21** [comment]
Oh, yes. Dennis is not here yet so I don't think he will get to it until late afternoon. I would be happy to clean it up and merge it without the test, if you want it now. Maybe Dennis can add test later.

**Comment by LenkaNovak** [comment]
Late afternoon with a test should be ok, thanks! I can work with this branch for now.

**Comment by dennisYatunin** [comment]
bors try

**Comment by dennisYatunin** [comment]
I added a unit test and made it so that this will (probably) work with restart files. I'll merge this in if it passes CI.

**Comment by dennisYatunin** [comment]
bors try

**Pull request merged**
