### PR TITLE
use dycore w in w_up filter

### PR DESCRIPTION
**Pull request by yairchn**
I am fixing a bug in the filter that was introduced in #877 for the filtering of updraft w

### CODE REVIEW

**Review by charleskawczynski — APPROVED** [review]

**Comment by trontrytel** [comment]
Looks like DYCOMS buoyancy, temperature and vertical velocity above the cloud top are very unhappy with the proposed changes. Bomex and TRMM look fine, so it's a little bit of a mystery right now for me. 

Before:

Screenshot 2022-10-09 at 18 46 39


After:

Screenshot 2022-10-09 at 18 44 08


I'll try setting it to zero to see what happens.

**Comment by trontrytel** [comment]
oh wow! Looks like no changes if we set it to zero 🎉 
Should we just o with that one @yairchn  (though I still don't understand why it even matters....)

**Comment by yairchn** [comment]
Thinking again about the problem. It might be that the value we set here has to be used in this type of filtering below 
`@. prog_up[i].ρarea =
            ifelse(Ic(prog_up_f[i].ρaw) <= 0, FT(0), prog_up[i].ρarea)`

**Comment by trontrytel** [comment]
Do you want me to test anything else or should we just merge it as is

**Comment by yairchn** [comment]
> Do you want me to test anything else or should we just merge it as is

we can try using the grid mean velocity, but also use it instead of the `0` I n these type of filtering 

`@. prog_up[i].ρarea = ifelse(Ic(prog_up_f[i].ρaw) <= 0, FT(0), prog_up[i].ρarea)` -->
`@. prog_up[i].ρarea = ifelse(Ic(prog_up_f[i].ρaw) <= w_gm, FT(0), prog_up[i].ρarea)`

**Comment by trontrytel** [comment]
Not needed. Replaced with EDMFX regularizations.

**Pull request closed without merging**
