### PR TITLE
Update nsight-systems version

### PR DESCRIPTION
**Pull request by charleskawczynski**
xref: https://github.com/CliMA/ClimaAtmos.jl/issues/2314#issuecomment-1802361713

### CODE REVIEW

**Review by simonbyrne — APPROVED** [review]

**Comment by szy21** [comment]
The regression test keeps failing. Not sure if it's random, or we need to update something for the merge queue.

**Comment by Sbozzolo** [comment]
Hasn't this passed here: https://buildkite.com/clima/climaatmos-ci/builds/14763 ?

**Comment by szy21** [comment]
> Hasn't this passed here: https://buildkite.com/clima/climaatmos-ci/builds/14763 ?

It did. That's why I'm confused. After this one passed it failed three times.

**Comment by Sbozzolo** [comment]
> > Hasn't this passed here: https://buildkite.com/clima/climaatmos-ci/builds/14763 ?
> 
> It did. That's why I'm confused. After this one passed it failed three times.

All the three jobs ran on `hpc-92-37`, which is a broadwell node. So, you got unlucky.

**Pull request merged**
