### PR TITLE
switch to third-order upwinding

### PR DESCRIPTION
**Pull request by simonbyrne**

### CODE REVIEW

**Comment by szy21** [comment]
The sphere cases look fine. You just need to update the mse I think. @charleskawczynski Should we turn off regression tests for moist cases for now? They are wrong anyway.

I don't know why the radiative equilibrium breaks with third-order upwinding. Maybe just the timestep is too large? I'll need to look into it.

**Comment by szy21** [comment]
Could we wait for #383 if possible?

**Review by szy21 — APPROVED** [review]

**Comment by charleskawczynski** [comment]
> @charleskawczynski Should we turn off regression tests for moist cases for now? They are wrong anyway. Edit: Let's think about the regression tests.

I think it's fine to leave them in-- they were designed to be easy to update so that we can use them while we're trying to get things working.

**Comment by szy21** [comment]
Ah, I forgot to push the radiation change so it still breaks. I'll push it now.

**Comment by charleskawczynski** [comment]
I'll rebase & merge

**Pull request merged**
