### PR TITLE
Skip dss with empty fields

### PR DESCRIPTION
**Pull request by charleskawczynski**
Fixes issue we're running into with https://github.com/CliMA/ClimaCore.jl/issues/1265

### CODE REVIEW

**Comment by sriharshakandala** [comment]
I think its best to have the exception handling code higher up rather at the location of the `weighted_dss` call. 
As discussed in https://github.com/CliMA/ClimaCore.jl/issues/1265 , there is no reason to call `tracer_hyperdiffusion_tendency!` when there are no tracers!

**Comment by charleskawczynski** [comment]
@dennisYatunin, any idea why this is resulting in behavioral changes for some jobs? cc @szy21, @simonbyrne

**Comment by szy21** [comment]
Hmm, the results actually look very strange.

**Comment by szy21** [comment]
Ah, I think I might know. For some quantities like `ᶜ∇²specific_tracers` (which is a NamedTuple), it should be `isempty(propertynames(x))`, but for some other quantities like `ᶜ∇²uₕ`, it should be just `isempty(x)`?

**Comment by charleskawczynski** [comment]
> Ah, I think I might know. For some quantities like `ᶜ∇²specific_tracers` (which is a NamedTuple), it should be `isempty(propertynames(x))`, but for some other quantities like `ᶜ∇²uₕ`, it should be just `isempty(x)`?

Ok, that makes sense.

I've been thinking about this a bit more, and I'm also wondering what broadcast expressions are doing with empty fields-- I think this is exercising an untested edge case in ClimaCore fields, cc @simonbyrne. Should we add some unit tests to ClimaCore so that we're sure this short circuits to no-ops?

**Comment by charleskawczynski** [comment]
This is fixing an issue that was fixed in the latest ClimaCore update.

**Pull request closed without merging**
