### PR TITLE
change default model top for non baroclinic wave examples

### PR DESCRIPTION
**Pull request by szy21**
Note that this will increase ci time by a factor of two. We can reduce t_end if needed. Any thoughts?

### CODE REVIEW

**Review by jiahe23 — APPROVED** [review]

**Comment by szy21** [comment]
Alright I decided to use a slightly weaker stretching so that we don't need to have too many levels and the ci won't take too much longer.

**Comment by szy21** [comment]
I'll need @charleskawczynski 's help on the regression test:) https://buildkite.com/clima/climaatmos-ci/builds/1017#_

**Comment by szy21** [comment]
The results look fine, although we need to change some `clim` to make the plots more useful. I'll go ahead and merge this and we can make better plots later.

**Pull request merged**
