### PR TITLE
Update deps

### PR DESCRIPTION
**Pull request by charleskawczynski**

### CODE REVIEW

**Comment by charleskawczynski** [comment]
Can someone (@nefrathenrici, or @valeriabarra, or @juliasloan25) review the results in here to make sure the physical results still look okay?

**Comment by valeriabarra** [comment]
There are some differences in `Covariance w qt` and `Covariance wT` plots for the `no lim ARS held suarez (ρe) equilmoist hightop sponge` job. I am not sure if those are significant. Probably @szy21 knows better.

**Comment by valeriabarra** [comment]
Baroclinc wave and aquaplanet jobs look identical to `main`

**Pull request merged**
