### PR TITLE
Change default ode solver to ARS343

### PR DESCRIPTION
**Pull request by charleskawczynski**
This PR changes the default ODE solver to ARS343, a continuation of #864.

### CODE REVIEW

**Comment by charleskawczynski** [comment]
The performance difference doesn't seem egregious, so I'm fine with merging. I'm assuming that the quality of the results were reviewed in #864. So I'm fine with merging and see how things go.

**Comment by valeriabarra** [comment]
I think we were also supposed to double the `dt`? (as per #863 )

**Pull request merged**
