### PR TITLE
CI pipeline: Add regular CI 1st-order upwind jobs

### PR DESCRIPTION
**Pull request by valeriabarra**
## Purpose 
This PR adds two jobs to the regular pipeline. These tests are part of #1503 

## Content
- Added moist BW and moist HS jobs with 1st-order upwinding on tracers only to the regular CI pipeline. These have been tested and pass.
- Added relevant MSE tables
- Updated ref counter

Review checklist

I have:
- followed the codebase contribution guide: https://clima.github.io/ClimateMachine.jl/latest/Contributing/
- followed the style guide: https://clima.github.io/ClimateMachine.jl/latest/DevDocs/CodeStyle/
- followed the documentation policy: https://github.com/CliMA/policies/wiki/Documentation-Policy
- checked that this PR does not duplicate an open PR.

In the Content, I have included 
- relevant unit tests, and integration tests, 
- appropriate docstrings on all functions, structs, and modules, and included relevant documentation.

- [x] I have read and checked the items on the review checklist.

### CODE REVIEW

**Comment by valeriabarra** [comment]
bors try

**Review by szy21 — APPROVED** [review]
Looks good, thanks! Could you also add the command for plotting, following other ci examples?

**Comment by valeriabarra** [comment]
> Looks good, thanks! Could you also add the command for plotting, following other ci examples?

Done. Thanks

**Pull request merged**
