### PR TITLE
Update to add Adaptive CFL option Callback

### PR DESCRIPTION
**Pull request by akshaysridhar**
Periodic Callback with user specified frequency.
Adds VerticalCFL, HorizontalCFL option.
Adds methods for get_nodal_distance [Move to ClimaCore] for Spaces
Adds methods for get_local_courant for combinations of models/ spaces
Adds method for get_velocities based on model types.

 Changes to be committed:
	modified:   src/Callbacks/Callbacks.jl
	modified:   src/Callbacks/callback.jl
	modified:   src/Models/Models.jl
	modified:   src/Models/Nonhydrostatic2DModels/equations_base_model.jl
	modified:   src/Models/Nonhydrostatic2DModels/nonhydrostatic_2d_model.jl
	modified:   src/Models/SingleColumnModels/single_column_model.jl
	modified:   test/test_cases/run_1d_ekman_column.jl
	modified:   test/test_cases/run_2d_rising_bubble.jl

### CODE REVIEW

**Comment by akshaysridhar** [comment]
bors try

**Comment by akshaysridhar** [comment]
bors try

**Review by bischtob — APPROVED** [review]
This looks good.

**Pull request merged**
