### PR TITLE
fix logging and comms logic

### LINKED ISSUE #838: Logging with multiple processes duplicates info
e.g. https://buildkite.com/clima/climaatmos-scaling/builds/252#018335a9-1ee5-4adf-9eb9-d74f789b3aff

Probably needs some rearranging of the driver file

### PR DESCRIPTION
**Pull request by simonbyrne**
## Purpose and Content
Fixes the duplicated log messages. Some of this was in #843, but I think got lost in the rebase.

## Benefits and Risks
Should simplify the logging and comms_ctx logic.

## Linked Issues
- Fixes #838 

## PR Checklist
- [ ] This PR has a corresponding issue OR is linked to an SDI.
- [ ] I have followed CliMA's codebase [contribution](https://clima.github.io/ClimateMachine.jl/latest/Contributing/) and [style](https://clima.github.io/ClimateMachine.jl/latest/DevDocs/CodeStyle/) guidelines OR N/A.
- [ ] I have followed CliMA's [documentation policy](https://github.com/CliMA/policies/wiki/Documentation-Policy).
- [ ] I have checked all issues and PRs and I certify that this PR does not duplicate an open PR.
- [ ] Unit tests are included OR N/A.
- [ ] Code used in an integration test OR N/A.
- [ ] All tests ran successfully on my local machine OR N/A.
- [ ] All classes, modules, and function contain appropriate docstrings OR N/A.
- [ ] Documentation has been added/updated OR N/A.

### CODE REVIEW

**Comment by charleskawczynski** [comment]
Sorry if I messed up the rebase, and thanks for fixing this!

**Comment by simonbyrne** [comment]
@LenkaNovak I've added the `@isdefined` here for the coupler.

**Pull request merged**
