### PR TITLE
Use SurfaceFluxes.jl v0.8.0

### PR DESCRIPTION
**Pull request by akshaysridhar**
Update sf functions to use v0.8.0 interface
	modified:   Project.toml
	modified:   src/surface_conditions/surface_conditions.jl

- [x] Check CI outcomes. 
- [x] Check longrun [outcomes. ](https://buildkite.com/clima/climaatmos-longruns/builds/1194#018b49cf-721a-46b1-b483-a839e62e5455)

### CODE REVIEW

**Review by szy21 — APPROVED** [review]
You can also remove all the `FLOAT_TYPE: "Float32"`, as that's the default.

**Review by trontrytel — APPROVED** [review]
Is that a good moment to bump the patch version in ClimaAtmos?

**Comment by akshaysridhar** [comment]
@sriharshakandala if you could verify the Project / Manifest toml updates w.r.t to the new SurfaceFluxes usage I think I can update the MSE tables via ref counter and merge this PR.

**Comment by szy21** [comment]
The AMIP simulation in the longrun seems to break immediately. Could you reduce dt by a factor of 2? No need to wait to see whether it works, we can just wait for today's longrun.

**Review by sriharshakandala — APPROVED** [review]

**Pull request merged**
