### PR TITLE
make GC deterministic in distributed

### PR DESCRIPTION
**Pull request by simonbyrne**
# PULL REQUEST

## Purpose and Content
This should reduce MPI Waitall time by manually triggering the GC across all processes at the same time.

## Benefits and Risks
The number of steps will require some tuning to avoid out-of-memory errors

## Linked Issues
- Item 3 of #635 
- Mentioned in #686
- Supersedes #687

## PR Checklist
- [x] This PR has a corresponding issue OR is linked to an SDI.
- [x] I have followed CliMA's codebase [contribution](https://clima.github.io/ClimateMachine.jl/latest/Contributing/) and [style](https://clima.github.io/ClimateMachine.jl/latest/DevDocs/CodeStyle/) guidelines OR N/A.
- [x] I have followed CliMA's [documentation policy](https://github.com/CliMA/policies/wiki/Documentation-Policy).
- [x] I have checked all issues and PRs and I certify that this PR does not duplicate an open PR.
- [x] I linted my code on my local machine prior to submission OR N/A.
- [x] Unit tests are included OR N/A.
- [x] Code used in an integration test OR N/A.
- [x] All tests ran successfully on my local machine OR N/A.
- [x] All classes, modules, and function contain docstrings OR N/A.
- [x] Documentation has been added/updated OR N/A.

### CODE REVIEW

**Comment by simonbyrne** [comment]
Testing out here https://buildkite.com/clima/climaatmos-scaling/builds/244

**Comment by simonbyrne** [comment]
I've added a small check so that GC is only called if free memory falls below a certain threshold

**Comment by simonbyrne** [comment]
It appears to boost scaling considerably, I think it's ready to go. Here are the low-res scaling benchmarks

Before:
low-resolution_sypd-old

After:
low-resolution_sypd-new

**Review by charleskawczynski — APPROVED** [review]
LGTM!

**Pull request merged**
