### PR TITLE
change y axis to linear scale in ci plots

### PR DESCRIPTION
**Pull request by szy21**
## Purpose 

Because this is preferred by Tapio:)

## Content

----
- [ ] I have read and checked the items on the review checklist.

### CODE REVIEW

**Comment by szy21** [comment]
Actually I like the previous scale for some cases. I’ll keep both options.

**Comment by Sbozzolo** [comment]
If you want linear scale, I think you can just remove the argument. That's the default.

**Comment by szy21** [comment]
> If you want linear scale, I think you can just remove the argument. That's the default.

Yeah, I kept the argument just to have more ticks. I don't care too much about it though, so I can remove it if you prefer.

**Comment by Sbozzolo** [comment]
No, it's fine.

**Pull request merged**
