### PR TITLE
Modify README in examples/hybrid/sphere/ 

### PR DESCRIPTION
**Pull request by jiahe23**

### CODE REVIEW

**Review by charleskawczynski — COMMENTED** [review]
I don't think we don't need `ClimaAtmos.jl/Manifest.toml`, but it's probably good to add all the others. Also, we can change the buildkite pipelines (for all the added Manifest.toml) by removing the `Pkg.develop()` lines.

**Comment by jiahe23** [comment]
> I don't think we don't need `ClimaAtmos.jl/Manifest.toml`, but it's probably good to add all the others. Also, we can change the buildkite pipelines (for all the added Manifest.toml) by removing the `Pkg.develop()` lines.

Yea... I will remove all the Manifest from this PR and rebase upon 309.

**Comment by jiahe23** [comment]
bors try

**Review by charleskawczynski — APPROVED** [review]

**Comment by charleskawczynski** [comment]
We hit the depot race condition.

**Pull request merged**
