### PR TITLE
Use env for repro tests, improve repro names

### PR DESCRIPTION
**Pull request by charleskawczynski**
This PR:
 - Removes the `reproducibility_test` flag in the yaml config, and we instead use an environment variable. I don't think experiments should explicitly need to worry about this, and there's no way for users to leverage this feature locally anyway, so an env flag seems more appropriate.
 - Improves some names to better reflect what some reproducibility test functions are doing.

### CODE REVIEW

**Comment by Sbozzolo** [comment]
What's the issue with the 4 GPU job?

**Review by Sbozzolo — APPROVED** [review]

**Comment by charleskawczynski** [comment]
> What's the issue with the 4 GPU job?

Not sure yet, still needs fixes..

**Comment by charleskawczynski** [comment]
I incremented the reference counter because I think it's far easier to "reset" our comparable references than to support comparing data exported from HDF5 formats (which we now use to support reproducibility tests for GPU jobs) with NC files (which we previously used).

**Comment by charleskawczynski** [comment]
If the restart job gets tripped up again, then I'll manually merge.

**Pull request merged**
