### PR TITLE
remove some regression tests

### PR DESCRIPTION
**Pull request by szy21**
## Purpose 

Also comments out the SSP+zalesak job

## Content

----
- [ ] I have read and checked the items on the review checklist.

### CODE REVIEW

**Comment by Sbozzolo** [comment]
What's the test `test_env` testing?

The gravity wave tests look like unit tests, can we move them out of buildkite and into the julia Test system?

**Comment by szy21** [comment]
> What's the test `test_env` testing?
> 
I don't know about this test. Maybe @charleskawczynski knows?

**Comment by charleskawczynski** [comment]
Sorry I'm late to this, `test_env` is the only buildkite job that launches julia with `julia --project=test`, which re-resolves the environment and tests ClimaAtmos with the latest versions (which is why that job is marked as `soft_fail: true`). It was my way to get a bit of a look-ahead to see what things coming down the pipeline were failing so that I could fix problems before people realized that they were coming.

**Comment by charleskawczynski** [comment]
(cc @szy21, @Sbozzolo, @sriharshakandala)

**Pull request merged**
