### PR TITLE
Update dependencies

### PR DESCRIPTION
**Pull request by charleskawczynski**
This PR updates the dependencies. ~Hmm, not sure why this isn't updating to the latest SurfaceFluxes.~ Things are updating but ClimaAtmos seems to be breaking with the latest release of ClimaCore.

### CODE REVIEW

**Comment by charleskawczynski** [comment]
🤞🏻

**Comment by szy21** [comment]
Isn't SurfaceFluxes already the latest?

**Comment by charleskawczynski** [comment]
> Isn't SurfaceFluxes already the latest?

Yes, SurfaceFluxes is already up to date. This PR does attempt to update ClimaCore, but it's breaking :confused:

**Comment by szy21** [comment]
> > Isn't SurfaceFluxes already the latest?
> 
> Yes, SurfaceFluxes is already up to date. This PR does attempt to update ClimaCore, but it's breaking 😕

Ah, ok, I was just replying to your comment on "not sure why this isn't updating to the latest SurfaceFluxes" :)

**Comment by charleskawczynski** [comment]
Ah, yeah, I think my first push was messed up, but it’s fixed now. I think my internet was poor and it couldn’t find the latest version locally and ended up downgrading me

**Pull request merged**
