### PR TITLE
Try comparison feature

### PR DESCRIPTION
**Pull request by charleskawczynski**
This PR tries out the plot comparison feature.

### CODE REVIEW

**Comment by charleskawczynski** [comment]
@Sbozzolo, can you take a look at this?

**Comment by charleskawczynski** [comment]
> Does `path` contain the NetCDF output?

Ah, it’s possible that we need to unpack them from the tar. I’ll try that first thing tomorrow

**Comment by Sbozzolo** [comment]
> > Does `path` contain the NetCDF output?
> 
> Ah, it’s possible that we need to unpack them from the tar. I’ll try that first thing tomorrow

Yes, they would need to be unpacked.

**Comment by charleskawczynski** [comment]
@Sbozzolo, can we merge this?

**Comment by Sbozzolo** [comment]
I think we still have to fix the margins, right?

**Comment by charleskawczynski** [comment]
> I think we still have to fix the margins, right?

Isn't that on the ClimaAnalysis side?

**Comment by Sbozzolo** [comment]
> > I think we still have to fix the margins, right?
> 
> Isn't that on the ClimaAnalysis side?

I don't think so, I think this will be in the `make_plots_generic` function in `ci_plots`. ClimaAnalysis plots in a given GridLayout, but it is up to main routine to properly arrange the GridLayouts. 

I will look into this.

**Comment by Sbozzolo** [comment]
I fixed the margin, more or less. I guess the folder path is determining the width.

I don't like this because it makes comparison harder.

**Comment by charleskawczynski** [comment]
> I fixed the margin, more or less. I guess the folder path is determining the width.
> 
> I don't like this because it makes comparison harder.

Interesting, looks cool!

**Comment by charleskawczynski** [comment]
Also, can we move the main branch to the left side? I like reading from left to right, and seeing where we were to where we are going 🙂

**Review by Sbozzolo — APPROVED** [review]

**Pull request merged**
