### PR TITLE
Add cli options, prep to unify driver

### PR DESCRIPTION
**Pull request by charleskawczynski**
This PR peels off some pieces from #346.

Hopefully this runs fine and I can return to #346.

### CODE REVIEW

**Review by jiahe23 — CHANGES_REQUESTED** [review]
Current changes look good to me. I do have some suggestions on the existing cli options that might be taken care of in this PR:
- default "--dt_save_to_sol" to zero;
- can we add "--dt_save_to_disk" as well?
- remove "--enable_threading" and do
```
if !is_distributed 
enable_threading() = true
end
```
in the `driver.jl`

**Comment by charleskawczynski** [comment]
I spoke with @jiahe23 about this, we'll
 - Keep `dt_save_to_sol` as is, since it was the default for all the jobs
 - Add `dt_save_to_disk` and default to zero
 - Default `enable_threading` to true

**Review by jiahe23 — APPROVED** [review]
lgtm

**Pull request merged**
