### PR TITLE
Use Thermodynamics.jl's T_guess

### PR DESCRIPTION
**Pull request by charleskawczynski**
This PR adds the use of Thermodynamics.jl's T_guess for specifying the initial guess for saturation adjustment.

### CODE REVIEW

**Comment by charleskawczynski** [comment]
@tapios, using this seems to fail for a few jobs:

 - `held suarez (ρe_tot) equilmoist monin_obukhov`

```
-----------------------------------------
maxiter reached in saturation_adjustment:
    Method=NewtonsMethod, T_guess=296.29517, e_int=57878.777, ρ=1.1330976, q_tot=0.017517533, T=295.5729, maxiter=8, tol=0.0001
┌ Error: Failure to establish a thermodynamic state at time 789261.5199129051
└ @ ClimaAtmos /central/scratch/esm/slurm-buildkite/climaatmos-ci/6176/climaatmos-ci/src/thermo_state.jl:108
-----------------------------------------
maxiter reached in saturation_adjustment:
    Method=NewtonsMethod, T_guess=296.29517, e_int=57878.777, ρ=1.1330976, q_tot=0.017517533, T=295.5729, maxiter=8, tol=0.0001
┌ Error: ClimaAtmos simulation crashed. Stacktrace for failed simulation
```

 - `held suarez (ρe_tot) equilmoist`

```
-----------------------------------------
maxiter reached in saturation_adjustment:
    Method=NewtonsMethod, T_guess=296.49347, e_int=58777.957, ρ=1.129504, q_tot=0.017831929, T=295.77725, maxiter=8, tol=0.0001
┌ Error: Failure to establish a thermodynamic state at time 818550.0
└ @ ClimaAtmos /central/scratch/esm/slurm-buildkite/climaatmos-ci/6176/climaatmos-ci/src/thermo_state.jl:108
-----------------------------------------
maxiter reached in saturation_adjustment:
    Method=NewtonsMethod, T_guess=296.49347, e_int=58777.957, ρ=1.129504, q_tot=0.017831929, T=295.77725, maxiter=8, tol=0.0001
┌ Error: ClimaAtmos simulation crashed. Stacktrace for failed simulation
```

**Comment by tapios** [comment]
If the initial guess here is temperature at the previous time step (or stage), the implied temperature changes per time step are unrealistic (several K per hour). Given that these are surface values in very moist and warm situations, probably the surface fluxes are unrealistically strong. So the problem does not seem to be SA but the setup.

1. Can you please change the tolerance to  `tol=0.0005`. Does that avoid this problem?
2. Please change the error when SA does not converge to a warning. We should not stop a run because of a minor (and usually immaterial) inaccuracy in temperature. It'll be good to have a warning message, but this is no reason to bail out.

**Comment by trontrytel** [comment]
Another stale PR from Thermodynamics. Do you think we need it? @szy21

**Comment by szy21** [comment]
Same, we want it but it didn't work :(

**Comment by tapios** [comment]
> Same, we want it but it didn't work :(

Why did it not work? I see my questions earlier were not answered.

Every model I know uses the previous timestep as initial guess for SA. If it doesn't work for us, we are doing something wrong.

**Comment by szy21** [comment]
> Why did it not work? I see my questions earlier were not answered.

I saw Charlie changed to tol=0.0005 in the latest commit, and it seemed to fail.

> Every model I know uses the previous timestep as initial guess for SA. If it doesn't work for us, we are doing something wrong.

I can look into it.

**Comment by trontrytel** [comment]
I'll take a look next week.

**Comment by charleskawczynski** [comment]
Superseded by #1648

**Pull request closed without merging**
