### PR TITLE
Update config for GPU DryBaroclinicWave benchmarks

### PR DESCRIPTION
**Pull request by sriharshakandala**
## Purpose 
Update z_elem to 63 for GPU DryBaroclinicWave benchmarks.

----
- [ ] I have read and checked the items on the review checklist.

### CODE REVIEW

**Comment by szy21** [comment]
Setting z_max to 55000 may cause unphysical initial condition for baroclinic wave. For testing the performance maybe keep z_max as 30000.

**Review by simonbyrne — APPROVED** [review]

**Pull request merged**
