### PR TITLE
compute precipitation tendencies after edmf

### PR DESCRIPTION
**Pull request by trontrytel**
This is a spinoff from https://github.com/CliMA/ClimaAtmos.jl/pull/1108. Testing to see how much difference we get just by changing the order of cimputations

### CODE REVIEW

**Review by charleskawczynski — APPROVED** [review]

**Comment by trontrytel** [comment]
@szy21 - can you look at the plots for the breaking case? I don't see any differences. So maybe we can merge it in?

**Comment by szy21** [comment]
Yes, they look good to me as well.

**Pull request merged**
