### PR TITLE
Upgrade to Julia 1.9.3

### PR DESCRIPTION
**Pull request by charleskawczynski**
This PR upgrades us to Julia 1.9.3

### CODE REVIEW

**Review by Sbozzolo — APPROVED** [review]
```
find . -name "Manifest.toml`

./perf/Manifest.toml
./examples/Manifest.toml
./docs/Manifest.toml
./.dev/Manifest.toml

find . -name "pipeline.yml"

./.buildkite/pipeline.yml
./.buildkite/gpu_pipeline/pipeline.yml
./.buildkite/longruns/pipeline.yml

grep -lr "1\.9\.2"

perf/Manifest.toml
examples/Manifest.toml
.dev/Manifest.toml
.buildkite/pipeline.yml
.buildkite/gpu_pipeline/pipeline.yml
.buildkite/longruns/pipeline.yml
```

As far as I can tell, all the files that had to be updated have been updated.

LGTM unless CI unexpectedly shows new failures.

**Comment by charleskawczynski** [comment]
We're even seeing these CUDA errors on CPU jobs..

**Pull request merged**
