### PR TITLE
Add ARS no limiter FCT to longrun pipeline

### PR DESCRIPTION
**Pull request by charleskawczynski**
xref: https://github.com/CliMA/ClimaAtmos.jl/issues/2344#issuecomment-1911089538.

### CODE REVIEW

**Review by szy21 — COMMENTED** [review]
Let's add the toml file following this line: https://github.com/CliMA/ClimaAtmos.jl/blob/b370eb872966793a8de7af0ea1da57d1b3cfd7b1/config/longrun_configs/longrun_hs_rhoe_equil_55km_nz63_0M.yml#L15

**Comment by szy21** [comment]
Also, it seems you are not using GPU? If so, maybe just put it in ./buildkite/longruns/pipeline.yml?

**Review by szy21 — APPROVED** [review]
Feel free to merge after making the changes.

**Comment by szy21** [comment]
Oh, one more thing. If you want plots, add the job_id to ci_plots.jl.

**Comment by charleskawczynski** [comment]
> Also, it seems you are not using GPU? If so, maybe just put it in ./buildkite/longruns/pipeline.yml?

Right, do you think it should be a CPU or GPU job?

**Comment by szy21** [comment]
> > Let's add the toml file following this line:
> > https://github.com/CliMA/ClimaAtmos.jl/blob/b370eb872966793a8de7af0ea1da57d1b3cfd7b1/config/longrun_configs/longrun_hs_rhoe_equil_55km_nz63_0M.yml#L15
> 
> What is this doing again?

This is adding the correct parameters for the rayleigh sponge.

**Comment by szy21** [comment]
> > Also, it seems you are not using GPU? If so, maybe just put it in ./buildkite/longruns/pipeline.yml?
> 
> Right, do you think it should be a CPU or GPU job?

I was thinking using central cluster for this job (which is what longrun/pipeline.yml uses), as it may still change. We have been using CPUs for that pipeline. But if we can use both central CPU and GPU in the same pipeline, I think GPU is good too.
Basically I just want to keep longrun_gpu/pipeline.yml short as it is using the eight clima GPUs, and there are already seven jobs (I may move some out later).

**Comment by charleskawczynski** [comment]
> I was thinking using central cluster for this job (which is what longrun/pipeline.yml uses), as it may still change. We have been using CPUs for that pipeline. But if we can use both central CPU and GPU in the same pipeline, I think GPU is good too. Basically I just want to keep longrun_gpu/pipeline.yml short as it is using the eight clima GPUs, and there are already seven jobs (I may move some out later).

I'll leave it as CPU for now, but we can change it later if it seems needed.

**Comment by szy21** [comment]
> > I was thinking using central cluster for this job (which is what longrun/pipeline.yml uses), as it may still change. We have been using CPUs for that pipeline. But if we can use both central CPU and GPU in the same pipeline, I think GPU is good too. Basically I just want to keep longrun_gpu/pipeline.yml short as it is using the eight clima GPUs, and there are already seven jobs (I may move some out later).
> 
> I'll leave it as CPU for now, but we can change it later if it seems needed.

Sounds good. It seems you are using only one CPU. It will be very slow. Is that intended?

**Comment by charleskawczynski** [comment]
> Sounds good. It seems you are using only one CPU. It will be very slow. Is that intended?

I didn't know that, I thought all of the other jobs in `longrun/pipeline.yml` were also using CPU. I'm happy to switch it to a gpu job.

**Comment by szy21** [comment]
> > Sounds good. It seems you are using only one CPU. It will be very slow. Is that intended?
> 
> I didn't know that, I thought all of the other jobs in `longrun/pipeline.yml` were also using CPU. I'm happy to switch it to a gpu job.

Yes, but they are using multiple cpus. I think you need to specify slurm_ntasks and add srun before julia?

**Comment by szy21** [comment]
Should we close this? We are using SSPKnoth for most simulations now.

**Comment by charleskawczynski** [comment]
> Should we close this? We are using SSPKnoth for most simulations now.

Fine by me.

**Pull request closed without merging**
