### PR TITLE
Smagorinsky Lily Diffusion

### PR DESCRIPTION
**Pull request by LanaLubecke**
calculates D for smag_lily

changes maxiter to 8 and small fix in smaglily

## Purpose 
This code makes the simulation crash but I am submitting pull request so Zhaoyi can see my code.
-->

## Content

----
- [ ] I have read and checked the items on the review checklist.

### CODE REVIEW

**Comment by haakon-e** [comment]
This looks good overall! Could be good to add a comment or two in the implementation itself (e.g. a reference to a paper that describes the model, or _brief_ explanation of some of the variables).

**Comment by haakon-e** [comment]
# Mathematical formulation
From Akshay's paper, momentum (Eq. 4) has the following terms for sub grid-scale turbulence:
```math
\frac{\partial \boldsymbol{u}}{\partial t} +\nabla\cdot(\dots) 
= (\dots) 
- \nabla \cdot (\rho \boldsymbol{\tau})
- \nabla \cdot (\boldsymbol{d}_{q_t} \otimes \rho \boldsymbol{u})
```
where the second term should be negligible. For the first term, we parameterize the stress tensor $\boldsymbol{\tau}$ by (ref. Eq. 34)
```math
\boldsymbol{\tau} = - (2 \boldsymbol{\nu}_t \boldsymbol{S})
```
where $\boldsymbol{S}$ is the strain rate tensor, defined by
```math
\boldsymbol{S} = \frac{1}{2} \left( 
  \nabla \boldsymbol{u} 
+ (\nabla \boldsymbol{u})^T \right),
```
with components
```math
S_{ij} = \frac{1}{2} \left(
   \frac{\partial u_i}{\partial x_j}
+ \frac{\partial u_j}{\partial x_i}
\right).
```
In our implementation, we assume the turbulent viscosity tensor $\boldsymbol{\nu}_t$ is isotropic, i.e. $\boldsymbol{\nu}_t = \nu_t I$ for a turbulent viscosity scalar $\nu_t$, where $I$ is the identity matrix. We parameterize $\nu_t$ as
```math
\nu_t = (C_s \Delta)^2 \| \boldsymbol{S} \|
```
where $\| \boldsymbol{S} \|$ is the magnitude of the strain-rate tensor, defined as
```math
\| \boldsymbol{S} \| = \sqrt{2\sum_{i,j}S_{ij}S_{ij}}
```
This means we can write the sub grid-scale fluxes concisely as
```math
- \nabla \cdot \left(
  - 2\rho \nu_t \boldsymbol{S}
\right)
```
or
```math
-\nabla \cdot \left(
  -2\rho (C_s \Delta)^2 \| \boldsymbol{S} \| 
  \frac{1}{2} \left(
           \frac{\partial u_i}{\partial x_j}
        + \frac{\partial u_j}{\partial x_i}
        \right)
\right)
```
# Formulation in terms of ClimaAtmos 
In ClimaAtmos, horizontal and vertical velocities are computed separately,
TODO:
* Reformulate the above in terms of horizontal and vertical velocities (and be careful with density-scaling)
* State simplifications to velocity gradients for the strain-rate tensor

**Comment by szy21** [comment]
@akshaysridhar Could we close this?

**Comment by akshaysridhar** [comment]
Yes - this will be superseded. There are assumptions in this PR which we don't generally need to make.

**Pull request closed without merging**
