### PR TITLE
Reduce Nq in the GCM tests

### LINKED ISSUE #792: Reduce Nq to 4 in GCM cases.
For a straightforward performance benchmarking towards Tempest and a easy use of TempestRemap in ClimaCoupler, we need to reduce Nq to 4.

The corresponding changes in the configuration include element number, hyperviscosity, time step, etc. to achieve a stable simulation at the rough same resolution.

### PR DESCRIPTION
**Pull request by jiahe23**
# PULL REQUEST

## Purpose and Content
This PR reduces Nq to 4 for current GCM cases. Ne, hyperdiffusion, timestep are modified accordingly.

Please note:
This changes only focus on simulations using OrdinaryDiffEq with central difference vertical scheme but not those using ClimaTimeStepper or corrected upwinding scheme due to a parallel debugging work on CTS and FCT.

## Benefits and Risks
(State concisely the benefits to be derived from and the risks associated with this PR)

## Linked Issues
- Closes #792 

## PR Checklist
- [x] This PR has a corresponding issue OR is linked to an SDI.
- [x] I have followed CliMA's codebase [contribution](https://clima.github.io/ClimateMachine.jl/latest/Contributing/) and [style](https://clima.github.io/ClimateMachine.jl/latest/DevDocs/CodeStyle/) guidelines OR N/A.
- [x] I have followed CliMA's [documentation policy](https://github.com/CliMA/policies/wiki/Documentation-Policy).
- [x] I have checked all issues and PRs and I certify that this PR does not duplicate an open PR.
- [x] I linted my code on my local machine prior to submission OR N/A.
- [ ] Unit tests are included OR N/A.
- [ ] Code used in an integration test OR N/A.
- [x] All tests ran successfully on my local machine OR N/A.
- [ ] All classes, modules, and function contain docstrings OR N/A.
- [ ] Documentation has been added/updated OR N/A.

### CODE REVIEW

**Review by szy21 — APPROVED** [review]

**Comment by jiahe23** [comment]
bors try

**Comment by jiahe23** [comment]
bors try-

**Comment by jiahe23** [comment]
bors try

**Comment by charleskawczynski** [comment]
Sorry, #818 is fixing CI, so that needs to be merged first

**Pull request merged**
