### PR TITLE
Add equator-pole temperature gradient parameters for calibration

### PR DESCRIPTION
**Pull request by nefrathenrici**
The equator-pole temperature gradient parameters are currently hardcoded in the held-suarez tendency.
For our first calibration test, we need to calibrate on these, so they need to be modifiable parameters.
I have already added them to ClimaParameters.

### CODE REVIEW

**Comment by nefrathenrici** [comment]
bors try

**Comment by nefrathenrici** [comment]
bors cancel

**Comment by nefrathenrici** [comment]
bors try-

**Review by szy21 — APPROVED** [review]

**Pull request merged**
