### PR TITLE
Clean up scaling pipeline

### PR DESCRIPTION
**Pull request by nefrathenrici**
### Content
Modify the scaling pipeline to autogenerate the configuration files

Remove `config/scaling_configs`

Clean up scaling plots a bit

#### Current scaling run: 
https://buildkite.com/clima/climaatmos-scaling/builds/492

### CODE REVIEW

**Comment by sriharshakandala** [comment]
bors try

**Comment by sriharshakandala** [comment]
bors try

**Comment by nefrathenrici** [comment]
bors try

**Comment by nefrathenrici** [comment]
bors try

**Review by sriharshakandala — APPROVED** [review]

**Pull request merged**
