### PR TITLE
Turn off diagnostics and IO for GPU pipeline

### PR DESCRIPTION
**Pull request by sriharshakandala**
## Purpose 
Turn of diagnostics and IO for GPU pipeline

----
- [ ] I have read and checked the items on the review checklist.

### CODE REVIEW

**Review by akshaysridhar — APPROVED** [review]

**Comment by akshaysridhar** [comment]
See also #2521

**Review by szy21 — APPROVED** [review]

**Review by charleskawczynski — APPROVED** [review]

**Comment by szy21** [comment]
Actually, if we turn off diagnostics in all the GPU jobs, we are not testing if diagnostics work on GPU? @sriharshakandala @charleskawczynski Should we add one test?

**Comment by akshaysridhar** [comment]
> Actually, if we turn off diagnostics in all the GPU jobs, we are not testing if diagnostics work on GPU? @sriharshakandala @charleskawczynski Should we add one test?

We may need to update `ci_plots` entries, but it appears this CI test has active callbacks in a GPU run https://buildkite.com/clima/climaatmos-ci/builds/16435#018d6633-58f7-4a16-85c2-7ce236899682

**Comment by szy21** [comment]
> We may need to update `ci_plots` entries, but it appears this CI test has active callbacks in a GPU run https://buildkite.com/clima/climaatmos-ci/builds/16435#018d6633-58f7-4a16-85c2-7ce236899682

This one only has the most basic diagnostics though. For example, the error in #2579 won't be caught if the diagnostics are removed.

**Comment by akshaysridhar** [comment]
> > We may need to update `ci_plots` entries, but it appears this CI test has active callbacks in a GPU run https://buildkite.com/clima/climaatmos-ci/builds/16435#018d6633-58f7-4a16-85c2-7ce236899682
> 
> This one only has the most basic diagnostics though. For example, the error in #2579 won't be caught if the diagnostics are removed.

Fair point - thanks!

**Comment by sriharshakandala** [comment]
We can have a different pipeline for testing/tuning IO, diagnostics on the GPU. We can use this pipeline purely for GPU performance monitoring!

**Comment by szy21** [comment]
> We can have a different pipeline for testing/tuning IO, diagnostics on the GPU. We can use this pipeline purely for GPU performance monitoring!

Sounds good. Some of the config files in gpu_config are not used in the target GPU simulations - they are used in ClimaAtmos ci for GPU compatibility tests. I can add the diagnostics back to those config files (in #2622), if that sounds good to you.

**Comment by sriharshakandala** [comment]
> > We can have a different pipeline for testing/tuning IO, diagnostics on the GPU. We can use this pipeline purely for GPU performance monitoring!
> 
> Sounds good. Some of the config files in gpu_config are not used in the target GPU simulations - they are used in ClimaAtmos ci for GPU compatibility tests. I can add the diagnostics back to those config files (in #2622), if that sounds good to you.

Sure. We can also consider having separate config files for CI, GPU pipeline, GPU IO pipeline, etc.

**Pull request merged**
