### PR TITLE
Remove reduntant @timev for distributed timer.

### PR DESCRIPTION
**Pull request by sriharshakandala**

### CODE REVIEW

**Comment by charleskawczynski** [comment]
I might recommend grabbing elapsed time from `@timev`, since it also prints out allocations, gc calls etc., in addition to wall time. Seeing allocations and number of gc calls is occasionally helpful.

**Comment by sriharshakandala** [comment]
> I might recommend grabbing elapsed time from `@timev`, since it also prints out allocations, gc calls etc., in addition to wall time. Seeing allocations and number of gc calls is occasionally helpful.

We still use @timev for serial case.
For distributed case, and @timev printout from each process generates a clunky output!

**Comment by charleskawczynski** [comment]
> > I might recommend grabbing elapsed time from `@timev`, since it also prints out allocations, gc calls etc., in addition to wall time. Seeing allocations and number of gc calls is occasionally helpful.
> 
> We still use @Timev for serial case. For distributed case, a @Timev printout from each process generates a clunky output!

Ah, ok, sounds good!

**Comment by Timev** [comment]
Guys, I'm not going to commit anything here, please stop tagging me

**Comment by sriharshakandala** [comment]
> 

Apologies for the accidental tagging. The conversation was about a macro. All references were removed.

**Pull request merged**
