### PR TITLE
fix the Base.show for HybridPlane

### LINKED ISSUE #120: fix the Base.show for HybridPlane
**context**
Following the domain terminology, let us call the 3D domain a box and the 2D domain a plane. 

**bug**
The current hybrid plane (1+1D) displays "box" to IO [here](https://github.com/CliMA/ClimaAtmos.jl/blob/main/src/Domains/domain.jl#L220).

### PR DESCRIPTION
**Pull request by szy21**
Closes #120

### CODE REVIEW

**Comment by szy21** [comment]
bors try

**Review by jiahe23 — APPROVED** [review]
looks nice

**Comment by szy21** [comment]
bors try-

**Pull request merged**
