### PR TITLE
refactor remapping pipeline to share the weights

### PR DESCRIPTION
**Pull request by szy21**
## Purpose 

Refactor the remapping pipleline so the weightfile is only created once.

## To-do

I don't think this makes it much faster. Will still need to do parallel remapping in another PR.

### CODE REVIEW

**Review by charleskawczynski — COMMENTED** [review]
I definitely approve the overall idea of writing this in a way that we can share the weights, but I think there are a few changes that we can make to make this a bit more flexible. Alright if I push a commit?

**Comment by szy21** [comment]
> I definitely approve the overall idea of writing this in a way that we can share the weights, but I think there are a few changes that we can make to make this a bit more flexible. Alright if I push a commit?

Yes please feel free! I will be in a symposium today so will only get to this later tonight I think.

**Review by charleskawczynski — APPROVED** [review]
Actually, I don't think that this is really tested in our CI, so if you've tested this locally and it works, then I'm fine with merging as is.

Ultimately I'd like to add a convenience wrapper in ClimaCoreTempestRemap that does this sort of thing

**Pull request merged**
