### PR TITLE
Improve implicit diffusion solver

### PR DESCRIPTION
**Pull request by dennisYatunin**
## Purpose 

This PR replaces the Jacobi preconditioned stationary iterative solver for diffusion with a lower triangular solver. Using a simpler solver will hopefully improve both performance and stability.

## Content

----
- [ ] I have read and checked the items on the review checklist.

### CODE REVIEW

**Comment by dennisYatunin** [comment]
Longruns: https://buildkite.com/clima/climaatmos-longruns/builds/1361

It looks like the simulations with implicit diffusion are a bit faster. @szy21, when you have some time, could you take a look at these results?

**Comment by szy21** [comment]
I accidentally merged in some typos in diagnostics recently and as a result several longruns are failing. Could you rebase and start a build again?

**Comment by szy21** [comment]
Actually, maybe wait for a bit more. I noticed a general slowdown of 40% for the longrun and am trying to figure out which PR it is.

**Comment by szy21** [comment]
Hmm, I'm not sure. The performance seems pretty random. Let's just start a longrun build.

**Pull request merged**
