### PR TITLE
Update to CloudMicrophysics v0.11

### PR DESCRIPTION
**Pull request by trontrytel**

### CODE REVIEW

**Review by nefrathenrici — APPROVED** [review]

**Comment by charleskawczynski** [comment]
We need to apply the `.dev/up_deps.jl` script for this to have any effect.

**Comment by charleskawczynski** [comment]
Also, that won't work because the latest version of Krylov.jl is breaking due to an issue I'm now digging into. This PR will have to wait

**Comment by trontrytel** [comment]
I think I'm on the slightly older version of julia than the one here. I'll have to update mine before I run the script

**Comment by trontrytel** [comment]
ok - I will wait. Thanks!

**Comment by trontrytel** [comment]
Done via https://github.com/CliMA/ClimaAtmos.jl/pull/2047

**Pull request closed without merging**
