### PR TITLE
Subtract a reference state from the dycore equations

### LINKED ISSUE #1188: Subtract a reference state in the equations of motion
## Purpose
Subtract a reference state of pressure and density that is in (discrete) hydrostatic balance from the equation of motion.
 
## Cost/Benefits/Risks
Benefit: As noted in the COSMO documentation, the main effect of introducing a reference state is the reduction of numerical errors associated with the calculation of the pressure gradient forcing in case of sloping coordinate systems.
Risks: It may not help with numerical instability

## People and Personnel
(@ the personnel required/requested to implement the software solution)
- Lead: @szy21 
- Collaborators: @dennisYatunin 
- Reviewers: @Zhengyu-Huang @charleskawczynski 

## Results and deliverables

- Updated equations in the code
- Benchmark simulations with the same or improved results in terms of numerical stability
- Updated design doc

## Task Breakdown And Tentative Due Date
(A preliminary list of PRs and a preliminary timeline of PRs, milestones, and key results)
- [ ] Construct discrete hydrostatic balance #1186 
- [ ] Write down new equations of motion and Jacobians
- [ ] Modify the explicit and implicit tendency functions

## Proposed Delivery Date
Dec 16, 2022

### PR DESCRIPTION
**Pull request by szy21**
## Purpose 

Adds an option to subtract a reference state from the equation of motion. When `use_reference_state` is false, the reference pressure and density are set to zero. Closes #1188. 

Please ignore the change in `.buildkite/longruns/pipeline.yml`. That's for testing and I will revert the changes before merging.

## To-do

- Review ci and longrun results and modify the MSE table

## Content

- Modify the equations and jacobians in the code. The equations are in the design doc Section 2.6. The jacobians are in the code comment. We should move them when we clean up the design doc.
- Add a command line argument `use_reference_state` which is set to True by default. For tests with discrete hydrostatic balanced initial condition, it is set to False.

----
- [ ] I have read and checked the items on the review checklist.

### CODE REVIEW

**Review by tapios — APPROVED** [review]
LGTM

**Review by charleskawczynski — APPROVED** [review]
Code changes LGTM, maybe @dennisYatunin can review the jacobian part?

**Comment by szy21** [comment]
> Code changes LGTM, maybe @dennisYatunin can review the jacobian part?

Just chatted with Dennis and made a few changes as he suggested (e.g. changing `grad(p) - grad(p_ref)` to `grad(p - p_ref)`). I also updated the equations for \rhotheta and \rhoe_int. Could you take a look at the EDMF jobs when the latest build is done to make sure the changes in results are ok?

**Comment by szy21** [comment]
@charleskawczynski the performance test failed with a slight (1%) increase in allocation: https://buildkite.com/clima/climaatmos-ci/builds/6247#018535e7-a661-4e1f-bcef-81c346880ae2. Could you check where it is allocating and let me know if it is ok to increase the limit?

**Pull request merged**
