### PR TITLE
Un-weighted interpolation: revert to last working long-run.

### PR DESCRIPTION
**Pull request by akshaysridhar**
## Purpose 
Reverts status to last passing long-run build.
modified:   src/tendencies/advection.jl
modified:   src/tendencies/implicit/implicit_tendency.jl
Linked #1290
Linked #1273 

## Required before merge
- [x] Verify [CI-Buildkite](https://buildkite.com/clima/climaatmos-ci/builds/6758)
- [x] Verify [Long-run build](https://buildkite.com/clima/climaatmos-longruns/builds/782). 
- [x] Verify plot outcomes.

### CODE REVIEW

**Review by Zhengyu-Huang — APPROVED** [review]

**Comment by akshaysridhar** [comment]
@trontrytel Can you please help me check the EDMF plots and confirm that the changes to files are reasonable?

**Comment by trontrytel** [comment]
> @trontrytel Can you please help me check the EDMF plots and confirm that the changes to results are reasonable?

The EDMF cases look good to me. There is one case that is failing, but it's already marked as a soft fail. So it should be good to go.

**Review by trontrytel — APPROVED** [review]

**Comment by akshaysridhar** [comment]
> > @trontrytel Can you please help me check the EDMF plots and confirm that the changes to results are reasonable?
> 
> The EDMF cases look good to me. There is one case that is failing, but it's already marked as a soft fail. So it should be good to go.

Thanks for checking this!

**Pull request merged**
