### PR TITLE
Add ARS + lim + Zalesak jobs

### LINKED ISSUE #1733: Add ARS + lim + Zalesak longrun jobs
During the Sprint meeting today, it was said to use ARS343 + limiters + Zalesak upwinding for now. 

I'll add those to our longrun buildkite jobs.

### PR DESCRIPTION
**Pull request by valeriabarra**
## Purpose 
Adds ARS343 + limiters + Zalesak FCT jobs to our longrun targeted resolution pipeline.

Closes #1733 

Review checklist

I have:
- followed the codebase contribution guide: https://clima.github.io/ClimateMachine.jl/latest/Contributing/
- followed the style guide: https://clima.github.io/ClimateMachine.jl/latest/DevDocs/CodeStyle/
- followed the documentation policy: https://github.com/CliMA/policies/wiki/Documentation-Policy
- checked that this PR does not duplicate an open PR.

In the Content, I have included 
- relevant unit tests, and integration tests, 
- appropriate docstrings on all functions, structs, and modules, and included relevant documentation.

----
- [x] I have read and checked the items on the review checklist.

### CODE REVIEW

**Comment by valeriabarra** [comment]
@szy21 let me know if you don't want to keep all of these jobs, or if you also want to add coarse-resolution pipeline ones.

**Comment by valeriabarra** [comment]
To review plots of the results for the MBW and Aquaplanet cases, please see the corresponding rows in this [table](https://github.com/CliMA/ClimaAtmos.jl/issues/1691#issuecomment-1569220790) in the dedicated issue.

**Review by szy21 — APPROVED** [review]
Looks good. How about removing the SSP ones and adding them back when we are ready to switch to SSP? Or we can keep only one (e.g. moist baroclinic wave) just to make sure it is working.

**Comment by valeriabarra** [comment]
Weird that the longrun lim + ARS + zalesak baroclinic wave [broke](https://buildkite.com/clima/climaatmos-longruns/builds/1026#01887fa3-7099-4159-961d-acb71d9f5510), with the given `dt 200secs`. I had tested it on my branch (that was rebased onto `main` before some of the latest changes that refactored things out of the driver) and it worked fine (I showed results in the [table](https://github.com/CliMA/ClimaAtmos.jl/issues/1691#issuecomment-1569220790) in the Issue). 
@szy21 do you know what else might have changed?

**Comment by szy21** [comment]
I think this [PR](https://github.com/CliMA/ClimaAtmos.jl/pull/1713) is the only one that changes MSE recently. It's not clear to me whether that longrun breaks due to an actual error or a bad node though.

**Pull request merged**
