### PR TITLE
Remove EDMFX and rename AdvectiveEDMFX to PrognosticEDMFX

### LINKED ISSUE #2250: Remove EDMFX and rename AdvectiveEDMFX

### PR DESCRIPTION
**Pull request by szy21**
## Purpose 

Goodbye EDMFX :)

Closes #2250 

## To-do

- [x] Add an example for new diagnostics package for prognostic edmf

## Content

----
- [ ] I have read and checked the items on the review checklist.

### CODE REVIEW

**Comment by szy21** [comment]
Do we want to remove the `specific_sgs` function [here](https://github.com/CliMA/ClimaAtmos.jl/blob/76be7f0c37ac17d3d8229e47c29c6666af4e2ca9/src/utils/variable_manipulations.jl#L157), and all the functions in the same file that only used by EDMFX?

**Review by trontrytel — APPROVED** [review]

**Comment by trontrytel** [comment]
Thank you!

**Comment by trontrytel** [comment]
> Do we want to remove the `specific_sgs` function [here](https://github.com/CliMA/ClimaAtmos.jl/blob/76be7f0c37ac17d3d8229e47c29c6666af4e2ca9/src/utils/variable_manipulations.jl#L157), and all the functions in the same file that only used by EDMFX?

I vote to remove unused code. Unless you think we might need it again soon?

**Comment by szy21** [comment]
> > Do we want to remove the `specific_sgs` function [here](https://github.com/CliMA/ClimaAtmos.jl/blob/76be7f0c37ac17d3d8229e47c29c6666af4e2ca9/src/utils/variable_manipulations.jl#L157), and all the functions in the same file that only used by EDMFX?
> 
> I vote to remove unused code. Unless you think we might need it again soon?

They are already removed:)

**Pull request merged**
