### PR TITLE
Tag v0.16.1

### PR DESCRIPTION
**Pull request by sriharshakandala**
## Purpose
Update dependencies 
Tag v0.16.1

----
- [x] I have read and checked the items on the review checklist.

### CODE REVIEW

**Comment by szy21** [comment]
Maybe wait for #2141 ?

**Comment by charleskawczynski** [comment]
Yeah, we could do that or just bump the ref counter in this PR, I'm fine with either one. Maybe keep it separate for tracking CI sake (since it's technically behavior changing)?

**Review by charleskawczynski — APPROVED** [review]
LGTM, want to just rebase after #2141?

**Comment by charleskawczynski** [comment]
I rebased!

**Pull request merged**
