### PR TITLE
Add tracer advection to implicit tendency

### PR DESCRIPTION
**Pull request by dennisYatunin**
This PR moves the term for vertical advection of tracers from the explicit tendency to the implicit tendency, and it updates the Jacobian appropriately. Note that vertical advection is currently using the upwinding operator, but the Jacobian is still constructed as if there were no upwinding operator (this will be generalized in a later PR).

### CODE REVIEW

**Comment by szy21** [comment]
Could you please also change the [docs](https://clima.github.io/ClimaAtmos.jl/dev/equations/) to make it consistent? Thanks!

**Review by Zhengyu-Huang — APPROVED** [review]
Great work!

**Pull request merged**
