### PR TITLE
Hyperdiffusion (moisture) contribution to mass equation

### PR DESCRIPTION
**Pull request by akshaysridhar**
Update mass tendencies to reflect diffusive moisture tendencies.

### CODE REVIEW

**Comment by jiahe23** [comment]
https://github.com/CliMA/ClimaAtmos.jl/blob/main/examples/hybrid/sphere/baroclinic_wave_utilities.jl#L425

Currently, the vertical diffusion does not apply to density (applying zero tendency), but it incorporate the surface flux of rho-qt into tho

**Comment by szy21** [comment]
Let's add it to both hyperdiffusion and vertical diffusion.

**Review by jiahe23 — CHANGES_REQUESTED** [review]
based on the discussion on slack, I think we should also do it to vertical diffusion

**Comment by akshaysridhar** [comment]
> based on the discussion on slack, I think we should also do it to vertical diffusion

@jiahe23 Please see the updated PR ; if this looks OK ( + the buildkite updated mse tables ) I'll rebase with the updated tables in the postproc directory.

**Review by jiahe23 — APPROVED** [review]

**Pull request merged**
