### PR TITLE
Fix Wfact upwind cases

### LINKED ISSUE #1576: Bug in vertical transport Jacobian for upwinding
# Issue

In the investigation carried out in #1536 , we discovered that the the vertical transport Jacobian, [`vertical_transport_jac`](https://github.com/CliMA/ClimaAtmos.jl/blob/7d1bba56137206cc16eeb1ee6cf4d86a617f3870/src/tendencies/implicit/wfact.jl#L26), for both the `first_order` and `third_order` upwinding cases has a bug. This manifested only in some high-resolution cases (moist BW and moist HS) and only in a few columns of the Jacobian. 

## Describe the bug
We were adding a reference epsilon, `ref_εw` to `ᶠw`, but for some of the columns, this resulted in cancellation errors. 

## Proposed solution
Get rid of the `ref_εw` hack and instead use the same construct as in the central diff case, but be careful about the sign of `ᶠw` to preserve the correctness of the upwinding direction.

### PR DESCRIPTION
**Pull request by valeriabarra**
## Purpose 
This PR fixes a nasty bug in the [`vertical_transport_jac`](https://github.com/CliMA/ClimaAtmos.jl/blob/7d1bba56137206cc16eeb1ee6cf4d86a617f3870/src/tendencies/implicit/wfact.jl#L26), for both the `first_order` and `third_order` upwinding cases.
This manifested only in some high-resolution cases (moist BW and moist HS) and only in a few columns of the Jacobian.

We were adding a reference epsilon, `ref_εw` to `ᶠw`, but for some of the columns, this resulted in cancellation errors.

This PR will close #1576 

## Content
Solution implemented: 
- [x]  Modified the `ref_εw` hack, but instead of using `eps(FT)`, we make sure to add `eps(ᶠw.u₃)` to avoid cancellation errors with `ᶠw.u₃`.

Review checklist

I have:
- followed the codebase contribution guide: https://clima.github.io/ClimateMachine.jl/latest/Contributing/
- followed the style guide: https://clima.github.io/ClimateMachine.jl/latest/DevDocs/CodeStyle/
- followed the documentation policy: https://github.com/CliMA/policies/wiki/Documentation-Policy
- checked that this PR does not duplicate an open PR.

In the Content, I have included 
- relevant unit tests, and integration tests, 
- appropriate docstrings on all functions, structs, and modules, and included relevant documentation.

- [x] I have read and checked the items on the review checklist.

### CODE REVIEW

**Comment by valeriabarra** [comment]
This is currently being tested in the high-resolution longrun in this [build](https://buildkite.com/clima/climaatmos-longruns/builds/920)

**Review by charleskawczynski — APPROVED** [review]
The code changes look fine to me, but I'd like to add other reviewers to look at the numerics and implicit solve implementation details. cc @dennisYatunin, @Zhengyu-Huang, @szy21

**Comment by szy21** [comment]
> The code changes look fine to me, but I'd like to add other reviewers to look at the numerics and implicit solve implementation details. cc @dennisYatunin, @Zhengyu-Huang, @szy21

I think @dennisYatunin is the right person to review this:)

**Review by dennisYatunin — APPROVED** [review]
I'm not sure why the `one(w) * sign(w)` version doesn't work---the saturation adjustment errors don't have NaN's, and the temperatures and specific humidities in those errors are just slightly off. This is fine to merge in for now, even though it is a bit hacky. I'll try to figure out how to get the cleaner version working while I do the implicit solver revamp for EDFMX over the coming weeks.

**Comment by valeriabarra** [comment]
The longrun moist BW with first-order upwinding on tracers that was failing after only a few time steps now runs to completion. See this [build](https://buildkite.com/clima/climaatmos-longruns/builds/940#01879bab-7255-4f3f-874f-ebd74438aff3). I am going to add it to the longrun pipeline in a separate PR.

**Pull request merged**
