### PR TITLE
upgrade SurfaceFluxes

### PR DESCRIPTION
**Pull request by szy21**

### CODE REVIEW

**Comment by szy21** [comment]
bors try

**Comment by szy21** [comment]
bors try

**Comment by szy21** [comment]
@charleskawczynski Two EDMF GABLS jobs fail in this PR. They will be fixed by #724. But Anna and I think it doesn't make sense to combine these two PRs. So we are thinking about disabling these two tests in this PR, and adding them back in 724. What do you think?

**Comment by charleskawczynski** [comment]
Sounds good to me

**Comment by szy21** [comment]
Oh @charleskawczynski, do I need to Increment the reference counter as well if I _remove_ some regression tests?

**Comment by charleskawczynski** [comment]
> Oh @charleskawczynski, do I need to Increment the reference counter as well if I _remove_ some regression tests?

Yeah, or, I think, you could remove the entries from the mse table

**Review by charleskawczynski — APPROVED** [review]

**Pull request merged**
