### PR TITLE
Modify dt for failing long-run builds.

### PR DESCRIPTION
**Pull request by akshaysridhar**
Following longrun build (test) no. 1045, decrease timestep for 2 experiments in the target AMIP resolution list. 
- no lim ARS baroclinic wave
- SSP equilmoist baroclinic wave high resolution

### CODE REVIEW

**Review by szy21 — APPROVED** [review]
Does it fix the problem?

**Comment by akshaysridhar** [comment]
> 

Yes - see here for instance : https://buildkite.com/clima/climaatmos-longruns/builds/1045. The build was triggered to test larger dt in topo (this part was unsucessful) ; I had included reduced dt in the failing experiments in the two experiments mentioned above.

**Comment by akshaysridhar** [comment]
Runtime ends up being 6h15m for the no-lim ARS case, and 14h20m for the SSP equilmoist BW case.

**Comment by szy21** [comment]
Great, thanks!

**Pull request merged**
