### PR TITLE
Fix `boris_book` and `zalesak` implicit tendency BCs

### LINKED ISSUE #1611: Bug in `boris_book` and `zalesak` `vertical_transport` function boundary specification
During my investigation for Issues #1554 and #1562 I discovered a bug in the current implementation of the `vertical_transport` function, in the `src/tendencies/implicit/implicit_tendnecy.jl` with both the `boris_book` and `zalesak` upwinding modes. 

## Bug description
Basically, we're now wrapping the upwind operator in a `ᶠset_upwind_bcs` (which is a `SetBoundaryOperator`) call. But we're doing this only on the external call to upwinding operator, not also to the one that is internal to the second `ᶜdivᵥ` call, as it should be. 

To reproduce, run the following example with bounds-checking enabled:
```
julia --project=examples examples/hybrid/driver.jl --initial_condition MoistBaroclinicWave --moist equil --precip_model 0M --job_id sphere_zalesak_upwind_ssp_baroclinic_wave_rhoe_equilmoist --dt 150secs --dt_save_to_disk 1days --ode_algo SSP333 --max_newton_iters 3 --tracer_upwinding zalesak
```
which would run otherwise, without the bounds-checking. 

## Proposed solution 
Used another call to `` in the internal `ᶜdivᵥ` operator call, i.e., 
```
@. ᶜρχₜ = -(ᶜdivᵥ(
        ᶠwinterp(ᶜJ, ᶜρ) * ᶠset_upwind_bcs(
            ᶠupwind1(ᶠu³, ᶜχ) + ᶠfct_zalesak(
                ᶠupwind3(ᶠu³, ᶜχ) - ᶠupwind1(ᶠu³, ᶜχ),
                ᶜχ / dt,
                ᶜχ / dt - ᶜdivᵥ(ᶠwinterp(ᶜJ, ᶜρ) * ᶠset_upwind_bcs(ᶠupwind1(ᶠu³, ᶜχ))) / ᶜρ,
            ),
        ),
    ))
```

### PR DESCRIPTION
**Pull request by valeriabarra**
## Purpose 
This PR fixes the `boris_book` and `zalesak` operators in the implicit tendency function `vertical_tranport`. 

It closes #1611 and #1579

## Content
- Solution implemeneted: Added another call to `ᶠset_upwind_bcs` in the internal `ᶜdivᵥ` operator call
- Added relevant CI jobs (these are more than we need right now, but as soon as CI passes, I will remove the unnecessary ones, i.e. third order operator (without flux-corrector) and leave only `zalesak` jobs on both tracer and energy)
- Modified MSE tables and ref counter

Review checklist

I have:
- followed the codebase contribution guide: https://clima.github.io/ClimateMachine.jl/latest/Contributing/
- followed the style guide: https://clima.github.io/ClimateMachine.jl/latest/DevDocs/CodeStyle/
- followed the documentation policy: https://github.com/CliMA/policies/wiki/Documentation-Policy
- checked that this PR does not duplicate an open PR.

In the Content, I have included 
- relevant unit tests, and integration tests, 
- appropriate docstrings on all functions, structs, and modules, and included relevant documentation.

- [x] I have read and checked the items on the review checklist.

### CODE REVIEW

**Review by szy21 — APPROVED** [review]
Thanks for the bugfix! I think we could just keep the tracer and energy upwinding. But if you would like to keep the tracer upwinding for now for testing, that is fine as well.

**Comment by valeriabarra** [comment]
> Thanks for the bugfix! I think we could just keep the tracer and energy upwinding. But if you would like to keep the tracer upwinding for now for testing, that is fine as well.

Yes, as I mentioned in the PR description as soon as I see that all jobs in CI pass, I will reduce the jobs.

**Comment by valeriabarra** [comment]
@szy21 the MBW jobs run with the configuration of `dt` and Newton interactions found (they just take long and we have that problem with `Exit status -1 agent lost` that we've seen already). Can I reduce the MBW job with zalesak to 5 days? I'll work on finding the stable configuration for MHS.
And then in a follow-up branch I'll test the longrun configurations

**Comment by szy21** [comment]
> @szy21 the MBW jobs run with the configuration of `dt` and Newton interactions found (they just take long and we have that problem with `Exit status -1 agent lost` that we've seen already). Can I reduce the MBW job with zalesak to 5 days? I'll work on finding the stable configuration for MHS. And then in a follow-up branch I'll test the longrun configurations

Yes, just note that it won't generate any plots, as we make plots for day 8 and day 10 for baroclinic wave. Maybe just plot the results manually for now, and we can change the plotting script to plot the last day in another PR.

**Comment by valeriabarra** [comment]
> Yes, just note that it won't generate any plots, as we make plots for day 8 and day 10 for baroclinic wave. Maybe just plot the results manually for now, and we can change the plotting script to plot the last day in another PR.

Okay, for some reason now I cannot use the `plot_pipeline.jl` locally (or on the Cluster), because it breaks with the following error 
```
ERROR: LoadError: MethodError: no method matching pop!(::StepRange{Int64, Int64})
Closest candidates are:
  pop!(::DataStructures.RobinDict) at ~/.julia/packages/DataStructures/59MD0/src/robin_dict.jl:533
  pop!(::DataStructures.RobinDict{K, V}, ::Any) where {K, V} at ~/.julia/packages/DataStructures/59MD0/src/robin_dict.jl:499
  pop!(::DataStructures.RobinDict{K, V}, ::Any, ::Any) where {K, V} at ~/.julia/packages/DataStructures/59MD0/src/robin_dict.jl:527
```
but I plotted all plots manually for the moist BW job with zalesak on tracers only and put them in our [Box](https://caltech.box.com/s/njphuvsmfr4ghhj0iomuzk7wvhfeaqie), if you would like to review them.

**Comment by szy21** [comment]
The vertical velocity looks strange. As a reference, the vertical velocity of moist baroclinic wave at day 10 at level 1+half in some recent build looks like this:
image

**Comment by valeriabarra** [comment]
bors try

**Comment by valeriabarra** [comment]
Superseded by #1617 

I'll add the tests in a separate PR

**Comment by szy21** [comment]
u and v at day 10 at level 1 for reference:

u
image

v
image

**Pull request closed without merging**
