### PR TITLE
Add spectra in postprocessing pipeline

### PR DESCRIPTION
**Pull request by Sbozzolo**
The number of points was changed because ClimaCoreSpectra seem to require one dimension to be twice as much as to the other

### CODE REVIEW

**Comment by Sbozzolo** [comment]
@akshaysridhar, would you like to add the spectra you are interested in producing to `ci_plots.jl`?

To do that, just add a function call like
```julia
make_spectra_generic(
    simulation_path,
    vars;
    slicing_kwargs = ClimaAnalysis.Utils.kwargs(x = 0.0, time = LAST_SNAP),
)
```
to the relevant `make_plots` function.

**Comment by akshaysridhar** [comment]
@Sbozzolo The array size appears to be an assumption within the ClimaCore library - e.g. https://github.com/CliMA/ClimaCore.jl/blob/c83abb94cebc82046a392ba423cedd3681d2a93a/lib/ClimaCoreSpectra/test/gcm_visual_test.jl#L25. Otherwise this LGTM. Thanks! cc @LenkaNovak

**Comment by Sbozzolo** [comment]
Do you want the PR merge as it is, or would you like to add a commit to this PR that computes with your favorite spectra?

**Comment by akshaysridhar** [comment]
> Do you want the PR merge as it is, or would you like to add a commit to this PR that computes with your favorite spectra?

Merge as is I think; we can then keep updating the post-proc functions (same as choice of current default diagnostic outputs) as we add spectra for tke, and other variables.

**Pull request merged**
