### PR TITLE
Update dependencies

### PR DESCRIPTION
**Pull request by charleskawczynski**
This PR updates the dependencies.

### CODE REVIEW

**Comment by charleskawczynski** [comment]
Nice, I thought it was maybe a fluke, but here is a history of the GPU aquaplanet dyamond job:

 - Build [21499](https://buildkite.com/clima/climaatmos-ci/builds/21499#01930f2c-a20c-4dd7-9c37-f6564fadddda): sypd: 0.135
 - Build [21476](https://buildkite.com/clima/climaatmos-ci/builds/21476#0193058f-cbb3-4199-aa70-7e11ed901b50): sypd: 0.263
 - Build [21474](https://buildkite.com/clima/climaatmos-ci/builds/21474#019304ef-53fd-4943-9581-52a1509d13d0): sypd: 0.132
 - Build [21500](https://buildkite.com/clima/climaatmos-ci/builds/21500#019311aa-88f8-4344-a67a-f6d881552beb): sypd: 0.135
 - Build [21521](https://buildkite.com/clima/climaatmos-ci/builds/21521#01932104-c701-438a-acc6-ff0d2788385f): sypd: 0.588 (this PR's build)

**Comment by charleskawczynski** [comment]
I'm a bit confused by the incredible speed up in the end-to-end calibration test. @nefrathenrici, do you know what may be happening here?

**Comment by nefrathenrici** [comment]
Yep, the end-to-end test is exiting early as intended. I added a check to skip it if the cluster wait time is too long because the test schedules many slurm jobs.

**Comment by charleskawczynski** [comment]
This already passed CI, so I'm going to merge.

**Pull request merged**
