### PR TITLE
Add initial condition argument in longrun

### PR DESCRIPTION
**Pull request by szy21**
## Purpose 

cc @jiahe23 

## Content

----
- [ ] I have read and checked the items on the review checklist.

### CODE REVIEW

**Comment by jiahe23** [comment]
https://github.com/CliMA/ClimaAtmos.jl/blob/main/.buildkite/pipeline.yml#L234

**Comment by szy21** [comment]
cc @akshaysridhar, we forgot to change the argument for one topography case in ci in a previous PR

**Pull request merged**
