### PR TITLE
Temporarily disable profiling in scaling pipeline

### PR DESCRIPTION
**Pull request by sriharshakandala**
Temporarily disable profiling in scaling pipeline
Increase job times

----
- [ ] I have read and checked the items on the review checklist.

### CODE REVIEW

**Comment by simonbyrne** [comment]
Does the profiling add overhead?

**Comment by sriharshakandala** [comment]
The most expensive simulations are the `1 or 2` process ones. If we are ok with changing the scaling reference to `2` or `4` process run for high resolution simulations, that would help speedup the pipeline! (assuming perfect scaling upto `2` or `4` processes!)

**Comment by simonbyrne** [comment]
The other option would be to reduce how long we run the simulation (for the smaller numbers of procs).

**Comment by sriharshakandala** [comment]
> The other option would be to reduce how long we run the simulation (for the smaller numbers of procs).

We were targeting about `2000` samples for reducing variablility during the averaging process last year. But we can retry a smaller number!

**Comment by simonbyrne** [comment]
That's fair.

**Pull request merged**
