### PR TITLE
Set qt to zero for dry EDMF cases and add GABLS

### LINKED ISSUE #1960: Add GABLS for diagnostic EDMF
Add GABLS, make diagnostic EDMF work for dry case or set qt to zero.

### PR DESCRIPTION
**Pull request by szy21**
## Purpose 

Add GABLS and set qt to zero in dry edmf cases.
Closes #1960 

## Content

----
- [ ] I have read and checked the items on the review checklist.

### CODE REVIEW

**Comment by szy21** [comment]
This seems like an easy way to make EDMF run dry case with qt=0. @trontrytel Let me know what you think.

**Comment by trontrytel** [comment]
looks good to me. But it also looks like Bomex box breaks from `--nh_poly 1`

**Comment by szy21** [comment]
> looks good to me. But it also looks like Bomex box breaks from `--nh_poly 1`

Changing the domain size (which has a similar effect to changing hyperviscosity) make Bomex work but break Rico:( I am a bit unsure about using hyperdiffusion for poly order 1, and also it doesn't seem to help reduce ci time much, so I will just keep the default poly order 3 for now.

**Pull request merged**
