### PR TITLE
Use 3D curl in vector hyperdiffusion

### PR DESCRIPTION
**Pull request by simonbyrne**
## Purpose 
This switches to using the 3D spectral element curl (https://github.com/CliMA/ClimaCore.jl/pull/1425) in hyperdiffusion.

## To-do
- [ ] check that it is non-breaking

## Content

----
- [x] I have read and checked the items on the review checklist.

### CODE REVIEW

**Comment by simonbyrne** [comment]
https://buildkite.com/clima/climaatmos-longruns/builds/1161

**Review by szy21 — APPROVED** [review]
Is the behavior change as expected?

**Comment by simonbyrne** [comment]
There's probably some small numerical change, but it shouldn't be behavior changing.

**Comment by szy21** [comment]
> There's probably some small numerical change, but it shouldn't be behavior changing.

Right, I meant the mse change. The results look good to me.

**Comment by simonbyrne** [comment]
Longruns available here: https://buildkite.com/clima/climaatmos-longruns/builds/1166

@szy21 do they look okay?

**Comment by szy21** [comment]
The longrun looks good to me.

**Pull request merged**
