### PR TITLE
Allow for non-default keys in the parser

### LINKED ISSUE #1638: Allow unknown keys in the parser
## Describe the issue

The set of command line arguments supported by ClimaAtmos is a subset of that of downstream packages, such as the Coupler (which has its own additional Coupler-specific keys). 

## To reproduce
I found that the current Atmos behavior is not compatible with Coupler examples. While testing the current ClimaAtmos v0.11.0 in the Coupler, examples break on this [line](https://github.com/CliMA/ClimaAtmos.jl/blob/92ee08462187dafa522d1380ff714eb167314667/src/utils/cli_options.jl#L390). See for instance this [build](https://buildkite.com/clima/climacoupler-ci/builds/1175#0187e386-d51d-4c28-aa9e-a7d11b9f8273) in the Coupler.

## Proposed fix 
Allow for unknown keys in the parser to be skipped, e.g., by adding this line:
```
!haskey(defaults, k) && continue
```

### PR DESCRIPTION
**Pull request by valeriabarra**
## Purpose 
The purpose of this PR is to allow for unknown keys in the parser. This is needed to be compatible with downstream packages, such as the Coupler, which has its additional Coupler-specific keys. 

Closes #1638 

## Content
Solution implemented:
- Added a line to allow the parser to skip unknown keys

Review checklist

I have:
- followed the codebase contribution guide: https://clima.github.io/ClimateMachine.jl/latest/Contributing/
- followed the style guide: https://clima.github.io/ClimateMachine.jl/latest/DevDocs/CodeStyle/
- followed the documentation policy: https://github.com/CliMA/policies/wiki/Documentation-Policy
- checked that this PR does not duplicate an open PR.

In the Content, I have included 
- relevant unit tests, and integration tests, 
- appropriate docstrings on all functions, structs, and modules, and included relevant documentation.

- [x] I have read and checked the items on the review checklist.

### CODE REVIEW

**Comment by valeriabarra** [comment]
> Either way, this change is fine, to make it more robust you may want to also `!haskey(_parsed_args, k) && continue`

Thank you. But this is happening inside a `for` loop (for every `k` in `keys(_parsed_args)`), so `_parsed_args` will necessarily have every `k` in it.

**Comment by szy21** [comment]
@valeriabarra Just want to let you know that we only add issues to the github project, not PRs, so I removed it from the project. PRs that are linked to issues will be shown automatically.

**Comment by valeriabarra** [comment]
> @valeriabarra Just want to let you know that we only add issues to the github project, not PRs, so I removed it from the project. PRs that are linked to issues will be shown automatically.

Oh ok, sorry

**Comment by valeriabarra** [comment]
@dennisYatunin, @trontrytel this PR should not change anything in MSE tables or regression tests. Do you know what's going on with the EDMF failures in Buildkite?

**Comment by szy21** [comment]
Try rebasing main?

**Comment by valeriabarra** [comment]
> Try rebasing main?

I already did. It's up to date

**Comment by szy21** [comment]
Oh, I think I may break the regression test in the name change PR. Let me try to push a fix.

**Comment by szy21** [comment]
Should be fine after #1640. Sorry about the friction!

**Comment by charleskawczynski** [comment]
Looks like we need to increase the memory request for some jobs

**Comment by valeriabarra** [comment]
I'll clear the depot now

**Pull request merged**
